import { beforeEach, describe, expect, it } from 'vitest'
import studyMigration from '../supabase/migrations/202608020200_study_preferences.sql?raw'
import settingsSource from '../src/diary/pages/DiarySettingsPage.tsx?raw'
import calendarSource from '../src/diary/pages/CalendarSyncPage.tsx?raw'
import { createStudyGoal, distributeStudyGoal } from '../src/diary/study/scheduler'
import { DEFAULT_DIARY_DATA, type StudyTask } from '../src/diary/types'
import { localDiaryRepository } from '../src/diary/repository'

const goal=(values={})=>createStudyGoal({subject:'영어',title:'250페이지 완독',totalAmount:250,startDate:'2026-08-03',deadline:'2026-08-09',...values})
const task=(values:Partial<StudyTask>={}):StudyTask=>({id:'locked-1',goalId:'goal',scheduledDate:'2026-08-04',title:'고정 작업',startAmount:1,endAmount:2,plannedAmount:2,completedAmount:0,estimatedMinutes:20,status:'planned',isLocked:true,sortOrder:0,textColor:'#222222',backgroundColor:'#ffffff',borderColor:'#777777',notes:'',createdAt:'2026-08-01T00:00:00.000Z',updatedAt:'2026-08-01T00:00:00.000Z',isAutoGenerated:true,...values})

describe('결정론적 학습 분량 배분',()=>{
 it('250페이지를 7일에 정확히 배분한다',()=>{const result=distributeStudyGoal(goal());expect(result.ok).toBe(true);expect(result.days.reduce((sum,day)=>sum+day.amount,0)).toBe(250)})
 it('나머지가 있는 분량도 합계가 정확하다',()=>{const result=distributeStudyGoal(goal({totalAmount:101}));expect(result.total).toBe(101);expect(result.days.at(-1)?.endAmount).toBe(101)})
 it('제외 날짜에는 작업을 생성하지 않는다',()=>{const result=distributeStudyGoal(goal({excludedDates:['2026-08-05']}));expect(result.days.some(day=>day.date==='2026-08-05')).toBe(false);expect(result.total).toBe(250)})
 it('설정한 요일만 사용한다',()=>{const result=distributeStudyGoal(goal({availableWeekdays:[1,2,3,4,5]}));expect(result.days.every(day=>![0,6].includes(new Date(`${day.date}T00:00:00`).getDay()))).toBe(true)})
 it('하루 최대 분량을 넘지 않는다',()=>{const result=distributeStudyGoal(goal({totalAmount:70,maxDailyAmount:10}));expect(result.ok).toBe(true);expect(Math.max(...result.days.map(day=>day.amount))).toBeLessThanOrEqual(10)})
 it('이미 완료한 분량을 제외한다',()=>{const result=distributeStudyGoal(goal({completedAmount:50}));expect(result.total).toBe(200);expect(result.days[0].startAmount).toBe(51)})
 it('고정 작업을 재배분 후에도 같은 ID로 유지한다',()=>{const value=goal({id:'goal',totalAmount:10});const locked=task();const result=distributeStudyGoal(value,[locked]);expect(result.tasks.find(item=>item.id===locked.id)).toEqual(locked);expect(result.total).toBe(10)})
 it('불가능한 최대 분량을 구체적으로 감지한다',()=>{const result=distributeStudyGoal(goal({totalAmount:180,startDate:'2026-08-03',deadline:'2026-08-06',maxDailyAmount:30}));expect(result.ok).toBe(false);expect(result.errors.join(' ')).toContain('하루 최소')})
 it('부분 완료 후 남은 분량만 재배분한다',()=>{const partial=task({id:'partial',goalId:'goal',plannedAmount:40,completedAmount:25,status:'partial',isLocked:false,startAmount:1,endAmount:40});const result=distributeStudyGoal(goal({id:'goal',totalAmount:40,completedAmount:25}),[partial]);expect(result.total).toBe(15);expect(result.tasks.every(item=>item.id!=='partial')).toBe(true)})
 it('재배분 후 중복 작업 ID가 없다',()=>{const result=distributeStudyGoal(goal());expect(new Set(result.tasks.map(item=>item.id)).size).toBe(result.tasks.length)})
 it('Monthly와 Weekly가 동일한 작업 상태 객체를 사용한다',()=>{const shared=[task({status:'planned'})];shared[0]={...shared[0],status:'completed',completedAmount:2};const monthly=shared.find(item=>item.id==='locked-1'),weekly=shared.find(item=>item.id==='locked-1');expect(monthly).toBe(weekly);expect(weekly?.status).toBe('completed')})
})

describe('환경설정, 한국어, DEMO_MODE 무결성',()=>{
 const memory=new Map<string,string>()
 beforeEach(()=>{memory.clear();Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:(key:string)=>memory.get(key)??null,setItem:(key:string,value:string)=>memory.set(key,value),removeItem:(key:string)=>memory.delete(key)}})})
 it('글씨 크기 설정이 저장 후 복원된다',async()=>{const data=structuredClone(DEFAULT_DIARY_DATA);data.preferences.fontScale=130;await localDiaryRepository.save(data);expect((await localDiaryRepository.load()).preferences.fontScale).toBe(130)})
 it('색상 설정이 저장 후 복원된다',async()=>{const data=structuredClone(DEFAULT_DIARY_DATA);data.preferences.defaultBackgroundColor='#112233';await localDiaryRepository.save(data);expect((await localDiaryRepository.load()).preferences.defaultBackgroundColor).toBe('#112233')})
 it('설정 화면 주요 문구가 한국어다',()=>{for(const text of ['설정','글씨 크기','색상 및 테마','플래너 표시 분량','기본값으로 되돌리기'])expect(settingsSource).toContain(text)})
 it('캘린더 연동 화면 주요 문구가 한국어다',()=>{for(const text of ['캘린더 연동','지금 동기화','연결 해제','구독 주소 복사','구독 주소 재발급'])expect(calendarSource).toContain(text)})
 it('DEMO_MODE 학습 목표와 작업이 새로고침 후 유지된다',async()=>{const data=structuredClone(DEFAULT_DIARY_DATA);data.studyGoals=[goal({id:'goal'})];data.studyTasks=[task({goalId:'goal'})];await localDiaryRepository.save(data);const restored=await localDiaryRepository.load();expect(restored.studyGoals).toHaveLength(1);expect(restored.studyTasks).toHaveLength(1)})
 it('새 테이블 RLS와 안전 제약이 존재한다',()=>{for(const table of ['user_preferences','study_goals','study_tasks'])expect(studyMigration).toContain(`public.${table}`);expect(studyMigration).toContain('enable row level security');expect(studyMigration).toContain('completed_amount<=planned_amount');expect(studyMigration).toContain('study_tasks_external_unique')})
})
