import { useEffect, useRef, useState } from 'react'
import type { BrainstormBoard, BrainstormNode } from '../types'
import { newBoard, newEdge, newNode, useDiaryStore } from '../store'

export function BrainstormPage(){
 const store=useDiaryStore();const [boardId,setBoardId]=useState(store.boards[0]?.id);const board=store.boards.find(b=>b.id===boardId)??store.boards[0];const [draft,setDraft]=useState<BrainstormBoard>(board);const [selected,setSelected]=useState<string[]>([]);const [zoom,setZoom]=useState(1);const [history,setHistory]=useState<BrainstormBoard[]>([]);const [future,setFuture]=useState<BrainstormBoard[]>([]);const [connectFrom,setConnectFrom]=useState<string>();const drag=useRef<{id:string;x:number;y:number;ox:number;oy:number}|undefined>(undefined)
 useEffect(()=>{if(board){setDraft(board);setSelected([]);setHistory([]);setFuture([])}},[board?.id])
 useEffect(()=>{const timer=setTimeout(()=>{if(draft)void store.saveBoard({...draft,updatedAt:new Date().toISOString()})},500);return()=>clearTimeout(timer)},[draft])
 const commit=(next:BrainstormBoard)=>{setHistory(h=>[...h.slice(-29),draft]);setFuture([]);setDraft(next)}
 const addNode=()=>commit({...draft,nodes:[...draft.nodes,newNode(draft.id,120+draft.nodes.length*24,120+draft.nodes.length*20)]})
 const removeSelected=()=>{if(!selected.length)return;commit({...draft,nodes:draft.nodes.filter(n=>!selected.includes(n.id)),edges:draft.edges.filter(e=>!selected.includes(e.sourceId)&&!selected.includes(e.targetId))});setSelected([])}
 const removeNode=(id:string)=>commit({...draft,nodes:draft.nodes.filter(n=>n.id!==id),edges:draft.edges.filter(e=>e.sourceId!==id&&e.targetId!==id)})
 const undo=()=>{const previous=history.at(-1);if(!previous)return;setFuture(f=>[draft,...f]);setHistory(h=>h.slice(0,-1));setDraft(previous)};const redo=()=>{const next=future[0];if(!next)return;setHistory(h=>[...h,draft]);setFuture(f=>f.slice(1));setDraft(next)}
 useEffect(()=>{const key=(e:KeyboardEvent)=>{const editing=(e.target as HTMLElement)?.matches('input,textarea,[contenteditable]');if(editing)return;if(e.key.toLowerCase()==='n'){e.preventDefault();addNode()}if(['Delete','Backspace'].includes(e.key)){e.preventDefault();removeSelected()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();void store.saveBoard(draft)}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)})
 const updateNode=(id:string,values:Partial<BrainstormNode>)=>setDraft(v=>({...v,nodes:v.nodes.map(n=>n.id===id?{...n,...values,updatedAt:new Date().toISOString()}:n)}))
 if(!draft)return null
 return <section className="brainstorm-page"><header><div><span>FREEFORM CANVAS</span><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><small>{store.saveState} · {new Date(draft.updatedAt).toLocaleTimeString()}</small></div><div className="canvas-toolbar"><button onClick={addNode}>+ Note <kbd>N</kbd></button><button onClick={undo} disabled={!history.length}>Undo</button><button onClick={redo} disabled={!future.length}>Redo</button><button onClick={()=>setZoom(z=>Math.max(.5,z-.1))}>−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.min(1.6,z+.1))}>＋</button><button onClick={()=>setZoom(1)}>Fit view</button></div></header><div className="board-tabs">{store.boards.map(b=><button className={b.id===draft.id?'active':''} key={b.id} onClick={()=>setBoardId(b.id)}>{b.name}</button>)}<button onClick={()=>{const b=newBoard();void store.saveBoard(b);setBoardId(b.id)}}>＋ New board</button><button disabled={store.boards.length===1} onClick={()=>{if(confirm('Delete this board?')){const fallback=store.boards.find(b=>b.id!==draft.id)??store.boards[0];void store.deleteBoard(draft.id);setBoardId(fallback.id)}}}>Delete board</button></div>
  <div className="brainstorm-viewport" onPointerMove={e=>{if(!drag.current)return;const rect=e.currentTarget.getBoundingClientRect();updateNode(drag.current.id,{x:(e.clientX-rect.left-drag.current.ox)/zoom,y:(e.clientY-rect.top-drag.current.oy)/zoom})}} onPointerUp={()=>{if(drag.current){setHistory(h=>[...h.slice(-29),board]);drag.current=undefined}}} onWheel={e=>{if(e.ctrlKey){e.preventDefault();setZoom(z=>Math.max(.5,Math.min(1.6,z-e.deltaY*.001)))}}}><div className="brainstorm-canvas" style={{transform:`scale(${zoom})`}}><svg>{draft.edges.map(edge=>{const a=draft.nodes.find(n=>n.id===edge.sourceId);const b=draft.nodes.find(n=>n.id===edge.targetId);return a&&b?<line key={edge.id} x1={a.x+a.width/2} y1={a.y+a.height/2} x2={b.x+b.width/2} y2={b.y+b.height/2}/>:null})}</svg>{draft.nodes.map(node=><article key={node.id} className={`idea-card ${selected.includes(node.id)?'selected':''}`} style={{left:node.x,top:node.y,width:node.width,height:node.height,background:node.color}} onClick={e=>{e.stopPropagation();setSelected(s=>e.ctrlKey||e.metaKey?(s.includes(node.id)?s.filter(v=>v!==node.id):[...s,node.id]):[node.id])}}><div className="card-handle" onPointerDown={e=>{const rect=e.currentTarget.parentElement!.getBoundingClientRect();drag.current={id:node.id,x:e.clientX,y:e.clientY,ox:e.clientX-rect.left,oy:e.clientY-rect.top};e.currentTarget.setPointerCapture(e.pointerId)}}><span>•••</span><input type="color" value={node.color} onChange={e=>updateNode(node.id,{color:e.target.value})}/></div><input className="card-title" value={node.title} onChange={e=>updateNode(node.id,{title:e.target.value})}/><textarea value={node.body} onChange={e=>updateNode(node.id,{body:e.target.value})} placeholder="Write a thought…"/><footer><button onClick={()=>{if(connectFrom&&connectFrom!==node.id){commit({...draft,edges:[...draft.edges,newEdge(draft.id,connectFrom,node.id)]});setConnectFrom(undefined)}else setConnectFrom(node.id)}}>{connectFrom===node.id?'Choose target':'Connect'}</button><button onClick={()=>removeNode(node.id)}>×</button></footer><div className="resize-grip" onPointerDown={e=>{const startX=e.clientX,startY=e.clientY,w=node.width,h=node.height;const move=(ev:PointerEvent)=>updateNode(node.id,{width:Math.max(160,w+(ev.clientX-startX)/zoom),height:Math.max(110,h+(ev.clientY-startY)/zoom)});const up=()=>{removeEventListener('pointermove',move);removeEventListener('pointerup',up)};addEventListener('pointermove',move);addEventListener('pointerup',up)}}/></article>)}</div></div>
 </section>
}
