import { useEffect, useRef, useState } from 'react'
import type { BrainstormBoard, BrainstormNode, DocBlock, DocBlockType } from '../types'
import { newBoard, newEdge, newNode, useDiaryStore } from '../store'

const BLOCK_TYPES:{type:DocBlockType;label:string;hint:string}[]=[{type:'title',label:'제목',hint:'T'},{type:'subtitle',label:'부제목',hint:'t'},{type:'heading',label:'소제목',hint:'H'},{type:'bullet',label:'• 글머리',hint:'•'},{type:'body',label:'본문',hint:'¶'}]

export function BrainstormPage(){
 const store=useDiaryStore();const [boardId,setBoardId]=useState(store.boards[0]?.id);const board=store.boards.find(b=>b.id===boardId)??store.boards[0];const [draft,setDraft]=useState<BrainstormBoard>(board);const [selected,setSelected]=useState<string[]>([]);const [zoom,setZoom]=useState(1);const [history,setHistory]=useState<BrainstormBoard[]>([]);const [future,setFuture]=useState<BrainstormBoard[]>([]);const [connectFrom,setConnectFrom]=useState<string>();const drag=useRef<{id:string;x:number;y:number;ox:number;oy:number}|undefined>(undefined)
 const [view,setView]=useState<'canvas'|'doc'>('canvas');const [focusedBlock,setFocusedBlock]=useState<string>();const blockRefs=useRef<Record<string,HTMLTextAreaElement|null>>({});const pendingFocus=useRef<string|undefined>(undefined)
 useEffect(()=>{if(board){setDraft(board);setSelected([]);setHistory([]);setFuture([])}},[board?.id])
 useEffect(()=>{if(pendingFocus.current){blockRefs.current[pendingFocus.current]?.focus();pendingFocus.current=undefined}})
 const setBlockText=(id:string,text:string)=>setDraft(v=>({...v,blocks:v.blocks.map(b=>b.id===id?{...b,text}:b)}))
 const setBlockType=(id:string,type:DocBlockType)=>{if(!id)return;commit({...draft,blocks:draft.blocks.map(b=>b.id===id?{...b,type}:b)});blockRefs.current[id]?.focus()}
 const addBlock=(afterId?:string,type:DocBlockType='body')=>{const nb:DocBlock={id:crypto.randomUUID(),type,text:''};const idx=afterId?draft.blocks.findIndex(b=>b.id===afterId)+1:draft.blocks.length;const blocks=[...draft.blocks.slice(0,idx),nb,...draft.blocks.slice(idx)];pendingFocus.current=nb.id;commit({...draft,blocks})}
 const removeBlock=(id:string)=>{const idx=draft.blocks.findIndex(b=>b.id===id);const prev=draft.blocks[idx-1];pendingFocus.current=prev?.id;commit({...draft,blocks:draft.blocks.filter(b=>b.id!==id)})}
 useEffect(()=>{const timer=setTimeout(()=>{if(draft)void store.saveBoard({...draft,updatedAt:new Date().toISOString()})},500);return()=>clearTimeout(timer)},[draft])
 const commit=(next:BrainstormBoard)=>{setHistory(h=>[...h.slice(-29),draft]);setFuture([]);setDraft(next)}
 const addNode=()=>commit({...draft,nodes:[...draft.nodes,newNode(draft.id,120+draft.nodes.length*24,120+draft.nodes.length*20)]})
 const removeSelected=()=>{if(!selected.length)return;commit({...draft,nodes:draft.nodes.filter(n=>!selected.includes(n.id)),edges:draft.edges.filter(e=>!selected.includes(e.sourceId)&&!selected.includes(e.targetId))});setSelected([])}
 const removeNode=(id:string)=>commit({...draft,nodes:draft.nodes.filter(n=>n.id!==id),edges:draft.edges.filter(e=>e.sourceId!==id&&e.targetId!==id)})
 const undo=()=>{const previous=history.at(-1);if(!previous)return;setFuture(f=>[draft,...f]);setHistory(h=>h.slice(0,-1));setDraft(previous)};const redo=()=>{const next=future[0];if(!next)return;setHistory(h=>[...h,draft]);setFuture(f=>f.slice(1));setDraft(next)}
 useEffect(()=>{const key=(e:KeyboardEvent)=>{const editing=(e.target as HTMLElement)?.matches('input,textarea,[contenteditable]');if(editing)return;if(e.key.toLowerCase()==='n'){e.preventDefault();addNode()}if(['Delete','Backspace'].includes(e.key)){e.preventDefault();removeSelected()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();void store.saveBoard(draft)}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)})
 const updateNode=(id:string,values:Partial<BrainstormNode>)=>setDraft(v=>({...v,nodes:v.nodes.map(n=>n.id===id?{...n,...values,updatedAt:new Date().toISOString()}:n)}))
 if(!draft)return null
 return <section className="brainstorm-page"><header><div><span>FREEFORM CANVAS</span><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><small>{store.saveState} · {new Date(draft.updatedAt).toLocaleTimeString()}</small></div><div className="canvas-toolbar"><span className="view-switch"><button className={view==='canvas'?'active':''} onClick={()=>setView('canvas')}>캔버스</button><button className={view==='doc'?'active':''} onClick={()=>setView('doc')}>문서</button></span><button onClick={undo} disabled={!history.length}>Undo</button><button onClick={redo} disabled={!future.length}>Redo</button>{view==='canvas'&&<><button onClick={addNode}>+ Note <kbd>N</kbd></button><button onClick={()=>setZoom(z=>Math.max(.5,z-.1))}>−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.min(1.6,z+.1))}>＋</button><button onClick={()=>setZoom(1)}>Fit view</button></>}</div></header><div className="board-tabs">{store.boards.map(b=><button className={b.id===draft.id?'active':''} key={b.id} onClick={()=>setBoardId(b.id)}>{b.name}</button>)}<button onClick={()=>{const b=newBoard();void store.saveBoard(b);setBoardId(b.id)}}>＋ New board</button><button disabled={store.boards.length===1} onClick={()=>{if(confirm('Delete this board?')){const fallback=store.boards.find(b=>b.id!==draft.id)??store.boards[0];void store.deleteBoard(draft.id);setBoardId(fallback.id)}}}>Delete board</button></div>
  {view==='doc'&&<div className="doc-editor"><div className="doc-toolbar"><span>블록 서식:</span>{BLOCK_TYPES.map(bt=><button key={bt.type} disabled={!focusedBlock} className={focusedBlock&&draft.blocks.find(b=>b.id===focusedBlock)?.type===bt.type?'active':''} title={bt.label} onMouseDown={e=>{e.preventDefault();if(focusedBlock)setBlockType(focusedBlock,bt.type)}}>{bt.label}</button>)}<span className="doc-hint">Enter=새 블록 · Shift+Enter=줄바꿈 · 빈 블록에서 Backspace=삭제</span></div>
   <div className="doc-body">{draft.blocks.length===0&&<button className="doc-empty" onClick={()=>addBlock(undefined,'title')}>여기를 눌러 문서 작성을 시작하세요</button>}
    {draft.blocks.map(block=><div className={`doc-block doc-${block.type}`} key={block.id}>{block.type==='bullet'&&<span className="doc-bullet-mark">•</span>}<textarea ref={el=>{blockRefs.current[block.id]=el}} rows={Math.max(1,block.text.split('\n').length)} value={block.text} placeholder={block.type==='title'?'제목':block.type==='subtitle'?'부제목':block.type==='heading'?'소제목':block.type==='bullet'?'목록 항목':'본문을 입력하세요'} onFocus={()=>setFocusedBlock(block.id)} onChange={e=>setBlockText(block.id,e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();addBlock(block.id,block.type==='bullet'?'bullet':'body')}else if(e.key==='Backspace'&&block.text===''&&draft.blocks.length>1){e.preventDefault();removeBlock(block.id)}}}/></div>)}
    {draft.blocks.length>0&&<button className="doc-add-block" onClick={()=>addBlock(draft.blocks.at(-1)?.id,'body')}>＋ 블록 추가</button>}</div></div>}
  {view==='canvas'&&<div className="brainstorm-viewport" onPointerMove={e=>{if(!drag.current)return;const rect=e.currentTarget.getBoundingClientRect();updateNode(drag.current.id,{x:(e.clientX-rect.left-drag.current.ox)/zoom,y:(e.clientY-rect.top-drag.current.oy)/zoom})}} onPointerUp={()=>{if(drag.current){setHistory(h=>[...h.slice(-29),board]);drag.current=undefined}}} onWheel={e=>{if(e.ctrlKey){e.preventDefault();setZoom(z=>Math.max(.5,Math.min(1.6,z-e.deltaY*.001)))}}}><div className="brainstorm-canvas" style={{transform:`scale(${zoom})`}}><svg>{draft.edges.map(edge=>{const a=draft.nodes.find(n=>n.id===edge.sourceId);const b=draft.nodes.find(n=>n.id===edge.targetId);return a&&b?<line key={edge.id} x1={a.x+a.width/2} y1={a.y+a.height/2} x2={b.x+b.width/2} y2={b.y+b.height/2}/>:null})}</svg>{draft.nodes.map(node=><article key={node.id} className={`idea-card ${selected.includes(node.id)?'selected':''}`} style={{left:node.x,top:node.y,width:node.width,height:node.height,background:node.color}} onClick={e=>{e.stopPropagation();setSelected(s=>e.ctrlKey||e.metaKey?(s.includes(node.id)?s.filter(v=>v!==node.id):[...s,node.id]):[node.id])}}><div className="card-handle" onPointerDown={e=>{const rect=e.currentTarget.parentElement!.getBoundingClientRect();drag.current={id:node.id,x:e.clientX,y:e.clientY,ox:e.clientX-rect.left,oy:e.clientY-rect.top};e.currentTarget.setPointerCapture(e.pointerId)}}><span>•••</span></div><input className="card-title" value={node.title} onChange={e=>updateNode(node.id,{title:e.target.value})}/><textarea value={node.body} onChange={e=>updateNode(node.id,{body:e.target.value})} placeholder="Write a thought…"/><footer><button onClick={()=>{if(connectFrom&&connectFrom!==node.id){commit({...draft,edges:[...draft.edges,newEdge(draft.id,connectFrom,node.id)]});setConnectFrom(undefined)}else setConnectFrom(node.id)}}>{connectFrom===node.id?'Choose target':'Connect'}</button><button onClick={()=>removeNode(node.id)}>×</button></footer><div className="resize-grip" onPointerDown={e=>{const startX=e.clientX,startY=e.clientY,w=node.width,h=node.height;const move=(ev:PointerEvent)=>updateNode(node.id,{width:Math.max(160,w+(ev.clientX-startX)/zoom),height:Math.max(110,h+(ev.clientY-startY)/zoom)});const up=()=>{removeEventListener('pointermove',move);removeEventListener('pointerup',up)};addEventListener('pointermove',move);addEventListener('pointerup',up)}}/></article>)}</div></div>}
 </section>
}
