import { useState } from 'react'
import { eventsToIcs } from '../utils/ics'
import { useDiaryStore } from '../store'
import { DEMO_MODE } from '../repository'
import { supabase } from '../../lib/supabase'

const randomToken=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),byte=>byte.toString(16).padStart(2,'0')).join('')
export function CalendarSyncPage(){
 const store=useDiaryStore(),calendar=store.calendar,[message,setMessage]=useState(''),[working,setWorking]=useState(false);const appUrl=import.meta.env.NEXT_PUBLIC_APP_URL||location.origin,googleConfigured=Boolean(supabase&&!DEMO_MODE),token=calendar.appleToken,supabaseUrl=import.meta.env.NEXT_PUBLIC_SUPABASE_URL as string|undefined,feedUrl=token?(DEMO_MODE?`${appUrl}/api/calendar/ics/${token}`:`${supabaseUrl}/functions/v1/calendar-feed/${token}`):''
 const patch=(values:Partial<typeof calendar>)=>void store.updateCalendar({...calendar,...values})
 const googleConnect=async()=>{if(!googleConfigured||!supabase){setMessage('Supabase와 Google OAuth 환경 변수를 먼저 설정해 주세요. DEMO_MODE 일정은 계속 사용할 수 있습니다.');return}setWorking(true);const{data,error}=await supabase.functions.invoke('google-calendar-oauth-start',{body:{returnTo:`${location.origin}/calendar-sync`}});setWorking(false);if(error||!data?.url)setMessage(error?.message||'Google 로그인 주소를 만들지 못했습니다.');else location.href=data.url}
 const syncNow=async()=>{if(!supabase)return;setWorking(true);const{data,error}=await supabase.functions.invoke('google-calendar-sync');setWorking(false);setMessage(error?`동기화 실패: ${error.message}`:`${data?.synced??0}개 일정을 동기화했습니다.`)}
 const disconnect=async()=>{if(!confirm('Google Calendar 연결을 해제할까요? 저장된 다이어리와 학습 계획은 유지됩니다.'))return;if(supabase){const{error}=await supabase.from('calendar_connections').delete().eq('provider','google');if(error){setMessage(`연결 해제 실패: ${error.message}`);return}}await store.updateCalendar({...calendar,googleConnected:false,googleEmail:''});setMessage('Google Calendar 연결을 해제했습니다.')}
 const regenerate=async()=>{if(token&&!confirm('구독 주소를 재발급할까요? 기존 주소는 즉시 만료됩니다.'))return;setWorking(true);if(DEMO_MODE||!supabase){await store.updateCalendar({...calendar,appleToken:randomToken()});setMessage('DEMO_MODE용 구독 주소를 만들었습니다. 실제 구독 피드는 Supabase 배포 후 사용할 수 있습니다.')}else{const{data,error}=await supabase.functions.invoke('calendar-token',{body:{regenerate:Boolean(token)}});if(error||!data?.token)setMessage(error?.message||'비공개 구독 주소를 발급하지 못했습니다.');else{await store.updateCalendar({...calendar,appleToken:data.token});setMessage('새 비공개 구독 주소를 발급했습니다. 안전한 곳에 보관해 주세요.')}}setWorking(false)}
 const download=()=>{const blob=new Blob([eventsToIcs(store.events,'DEAR MY DIARY',store.studyTasks,store.studyGoals,calendar)],{type:'text/calendar;charset=utf-8'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download='dear-my-diary.ics';anchor.click();URL.revokeObjectURL(url)}
 return <section className="settings-page-new"><header><span>연결</span><h1>캘린더 연동</h1><p>일반 일정과 학습 계획을 외부 캘린더에서도 확인할 수 있습니다.</p></header>{message&&<div className="notice" role="status">{message}</div>}
  <article className="connection-card"><div className="provider-mark google">G</div><div><h2>Google Calendar 연결</h2><p>OAuth를 사용해 일반 일정과 학습 계획을 안전하게 양방향 동기화합니다.</p>{calendar.googleConnected?<><strong>{calendar.googleEmail}</strong><small>마지막 동기화: {calendar.lastSyncedAt??'아직 없음'}</small></>:<small>연결되지 않음</small>}</div><div className="connection-actions">{calendar.googleConnected?<><button disabled={working} onClick={syncNow}>지금 동기화</button><label><input type="checkbox" checked={calendar.autoSync} onChange={event=>patch({autoSync:event.target.checked})}/>자동 동기화</label><button onClick={disconnect}>연결 해제</button></>:<button className="purple-button" disabled={working} onClick={googleConnect}>Google Calendar 연결</button>}</div></article>
  <article className="settings-card"><h2>Google Calendar 학습 계획 옵션</h2><div className="settings-form"><label>동기화할 항목<select value={calendar.googleContent} onChange={event=>patch({googleContent:event.target.value as typeof calendar.googleContent})}><option value="events">일반 일정만</option><option value="study">학습 계획만</option><option value="both">일반 일정과 학습 계획 모두</option></select></label><label>학습 계획 시간 형식<select value={calendar.googleStudyTimeMode} onChange={event=>patch({googleStudyTimeMode:event.target.value as typeof calendar.googleStudyTimeMode})}><option value="all-day">종일 일정</option><option value="timed">시간 일정</option></select></label></div><label className="switch-row"><input type="checkbox" checked={calendar.googleIncludeCompleted} onChange={event=>patch({googleIncludeCompleted:event.target.checked})}/>완료된 학습 계획 포함</label><label className="switch-row"><input type="checkbox" checked={calendar.googleCompletedPrefix} onChange={event=>patch({googleCompletedPrefix:event.target.checked})}/>완료 항목 제목에 완료 표시</label><div className="settings-form">{store.studyGoals.filter(goal=>!goal.deletedAt).map(goal=><label key={goal.id}>{goal.subject} 대상 캘린더<input value={calendar.subjectCalendars[goal.id]??calendar.googleCalendarId} onChange={event=>patch({subjectCalendars:{...calendar.subjectCalendars,[goal.id]:event.target.value}})} placeholder="primary"/></label>)}</div></article>
  <article className="connection-card apple-card"><div className="provider-mark apple">●</div><div><h2>Apple Calendar 구독</h2><p>Apple Calendar는 단방향 ICS 구독입니다. DEAR MY DIARY의 변경은 새로 고칠 때 반영되지만 Apple Calendar에서 수정한 내용은 가져오지 않습니다.</p>{feedUrl?<div className="private-url"><input readOnly type="password" value={feedUrl}/><button onClick={async()=>{await navigator.clipboard.writeText(feedUrl);setMessage('구독 주소를 복사했습니다.')}}>구독 주소 복사</button></div>:<small>아직 비공개 구독 주소가 없습니다.</small>}</div><div className="connection-actions"><button disabled={working} onClick={regenerate}>{token?'구독 주소 재발급':'비공개 주소 발급'}</button><button onClick={download}>ICS 다운로드</button></div></article>
  <article className="settings-card"><h2>Apple Calendar 포함 항목</h2><label className="switch-row"><input type="checkbox" checked={calendar.appleIncludeEvents} onChange={event=>patch({appleIncludeEvents:event.target.checked})}/>일반 일정 포함</label><label className="switch-row"><input type="checkbox" checked={calendar.appleIncludeStudy} onChange={event=>patch({appleIncludeStudy:event.target.checked})}/>학습 계획 포함</label><label className="switch-row"><input type="checkbox" checked={calendar.appleIncludeCompleted} onChange={event=>patch({appleIncludeCompleted:event.target.checked})}/>완료 항목 포함</label><label className="switch-row"><input type="checkbox" checked={calendar.appleIncludeNotes} onChange={event=>patch({appleIncludeNotes:event.target.checked})}/>메모 포함</label><label className="switch-row"><input type="checkbox" checked={calendar.appleIncludeEstimatedTime} onChange={event=>patch({appleIncludeEstimatedTime:event.target.checked})}/>예상 소요 시간 포함</label></article>
  <section className="apple-help"><h3>Apple Calendar에 추가하기</h3><ol><li>비공개 구독 주소를 복사합니다.</li><li>Mac에서는 Calendar → File → New Calendar Subscription을 엽니다.</li><li>주소를 붙여 넣고 새로 고침 주기를 선택합니다.</li><li>iPhone에서는 설정 → 캘린더 → 계정 → 구독 캘린더 추가를 사용합니다.</li></ol><p>구독 주소는 일정 피드의 비밀번호와 같습니다. 다른 사람과 공유하지 마세요.</p></section>
 </section>
}
