import { useEffect, useMemo, useRef, useState } from 'react'
import { format } from 'date-fns'
import { newComment, newEntry, useDiaryStore } from '../store'
import type { DiaryEntry, DiaryImage } from '../types'

export function DiaryEntryPage({ eventId, goBack }:{eventId:string;goBack():void}){
 const store=useDiaryStore();const event=store.events.find(e=>e.id===eventId);const existing=store.entries.find(e=>e.eventId===eventId);const [entry,setEntry]=useState<DiaryEntry>(()=>existing??newEntry(eventId));const [slide,setSlide]=useState(0);const [comment,setComment]=useState('');const [editingComment,setEditingComment]=useState<string>();const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);const inputRef=useRef<HTMLInputElement>(null)
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.matches('input,textarea,[contenteditable]'))return;if(e.key==='ArrowLeft')setSlide(v=>Math.max(0,v-1));if(e.key==='ArrowRight')setSlide(v=>Math.min(entry.images.length-1,v+1))};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[entry.images.length])
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[])
 const patch=(next:Partial<DiaryEntry>)=>{const updated={...entry,...next,updatedAt:new Date().toISOString()};setEntry(updated);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void store.saveEntry(updated),500)}
 const upload=async(files:FileList|null)=>{if(!files)return;const accepted=[...files].filter(file=>file.type.startsWith('image/')&&file.size<=5*1024*1024);if(accepted.length!==files.length)store.setToast('Some files were skipped. Use images up to 5 MB.');const images=await Promise.all(accepted.map((file,index)=>new Promise<DiaryImage>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({id:crypto.randomUUID(),entryId:entry.id,fileName:file.name,dataUrl:String(reader.result),sortOrder:entry.images.length+index,createdAt:new Date().toISOString()});reader.onerror=reject;reader.readAsDataURL(file)})));patch({images:[...entry.images,...images]});setSlide(entry.images.length)}
 const moveImage=(from:number,delta:number)=>{const to=from+delta;if(to<0||to>=entry.images.length)return;const images=[...entry.images];[images[from],images[to]]=[images[to],images[from]];patch({images:images.map((img,i)=>({...img,sortOrder:i}))});setSlide(to)}
 const comments=useMemo(()=>store.comments.filter(c=>c.entryId===entry.id).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)),[store.comments,entry.id])
 if(!event)return <section className="missing-page"><h1>Entry not found</h1><button onClick={goBack}>Back to planner</button></section>
 return <section className="diary-entry-page"><button className="back-link" onClick={goBack}>← Back to planner</button><header className="diary-profile"><div className="avatar">{store.profile.avatar?<img src={store.profile.avatar}/>:store.profile.displayName[0]}</div><div><b>{store.profile.displayName}</b><span>{store.profile.handle}</span></div><div className="linked-plan"><small>WRITING ABOUT</small><strong>{event.title}</strong><time>{format(new Date(event.startAt),'EEEE, MMMM d · HH:mm')}</time></div><span className="autosave-state">{store.saveState}</span></header>
  <div className="diary-photo-stage">{entry.images.length?<><img src={entry.images[slide]?.dataUrl} alt={entry.images[slide]?.fileName}/><button className="photo-prev" onClick={()=>setSlide(v=>Math.max(0,v-1))} aria-label="Previous photo">‹</button><button className="photo-next" onClick={()=>setSlide(v=>Math.min(entry.images.length-1,v+1))} aria-label="Next photo">›</button><div className="photo-tools"><button onClick={()=>moveImage(slide,-1)}>Move left</button><span>{slide+1} / {entry.images.length}</span><button onClick={()=>moveImage(slide,1)}>Move right</button><button className="danger-button" onClick={()=>{const images=entry.images.filter((_,i)=>i!==slide);patch({images});setSlide(Math.max(0,slide-1))}}>Remove</button></div></>:<button className="photo-empty" onClick={()=>inputRef.current?.click()}><b>Add photos</b><span>JPG, PNG, GIF or WebP · up to 5 MB</span></button>}<input ref={inputRef} hidden type="file" accept="image/*" multiple onChange={e=>void upload(e.target.files)}/></div>
  {entry.images.length>0&&<button className="add-more-photos" onClick={()=>inputRef.current?.click()}>+ Add more photos</button>}
  <div className="diary-writing"><input className="diary-title" value={entry.title} onChange={e=>patch({title:e.target.value})} placeholder="A title for this memory…"/><textarea value={entry.body} onChange={e=>patch({body:e.target.value})} placeholder="Write what happened, how it felt, and what you want to remember…" rows={7}/><div className="diary-meta"><label>Mood<select value={entry.mood} onChange={e=>patch({mood:e.target.value})}><option>calm</option><option>happy</option><option>excited</option><option>tired</option><option>sad</option><option>messy</option></select></label><label>Tags<input value={entry.tags.join(', ')} onChange={e=>patch({tags:e.target.value.split(',').map(v=>v.trim()).filter(Boolean)})} placeholder="friends, summer, study"/></label></div></div>
  <section className="comments-section"><h2>Comments</h2>{comments.map(item=><article key={item.id}><div className="mini-avatar">{store.profile.displayName[0]}</div><div><b>{store.profile.displayName}</b>{editingComment===item.id?<input autoFocus defaultValue={item.body} onBlur={e=>{void store.saveComment({...item,body:e.target.value,updatedAt:new Date().toISOString()});setEditingComment(undefined)}}/>:<p>{item.body}</p>}<time>{format(new Date(item.createdAt),'MMM d, HH:mm')}</time></div><div><button onClick={()=>setEditingComment(item.id)}>Edit</button><button onClick={()=>void store.deleteComment(item.id)}>Delete</button></div></article>)}{!comments.length&&<p className="empty-copy">Leave a small follow-up note for your future self.</p>}<form onSubmit={e=>{e.preventDefault();if(comment.trim()){void store.saveComment(newComment(entry.id,comment.trim()));setComment('')}}}><input value={comment} onChange={e=>setComment(e.target.value)} placeholder="Add a comment…"/><button className="purple-button">Post</button></form></section>
 </section>
}
