import { useRef, useState } from 'react'
import { DEFAULT_PREFERENCES, type PlannerDensity, type UserPreferences } from '../types'
import { useDiaryStore } from '../store'
import { contrastRatio } from '../utils/theme'

const colorFields: Array<[keyof UserPreferences,string]> = [
 ['defaultTextColor','기본 글씨 색'],['defaultBackgroundColor','기본 배경 색'],['secondaryBackgroundColor','보조 배경 색'],['accentColor','강조 색'],['calendarLineColor','달력 선 색'],['completedItemColor','완료 항목 색'],['selectedItemColor','선택 항목 색']
]
const densityValues:Record<Exclude<PlannerDensity,'custom'>,Partial<UserPreferences>>={
 relaxed:{monthlyVisibleEventCount:3,monthlyVisibleTaskCount:2,weeklyVisibleTaskCount:6,calendarCellHeight:160,eventCardGap:6,checklistRowHeight:42},
 default:{monthlyVisibleEventCount:4,monthlyVisibleTaskCount:3,weeklyVisibleTaskCount:8,calendarCellHeight:138,eventCardGap:3,checklistRowHeight:36},
 compact:{monthlyVisibleEventCount:6,monthlyVisibleTaskCount:5,weeklyVisibleTaskCount:12,calendarCellHeight:118,eventCardGap:1,checklistRowHeight:30}
}

export function DiarySettingsPage(){
 const store=useDiaryStore(),preferences=store.preferences;const fileRef=useRef<HTMLInputElement>(null);const [reduced,setReduced]=useState(localStorage.getItem('dmd-reduced-motion')==='1')
 const patch=(values:Partial<UserPreferences>)=>void store.updatePreferences({...preferences,...values})
 const density=(value:PlannerDensity)=>patch({plannerDensity:value,...(value==='custom'?{}:densityValues[value])})
 const exportData=()=>{const data={events:store.events,entries:store.entries,comments:store.comments,boards:store.boards,profile:store.profile,calendar:store.calendar,preferences:store.preferences,studyGoals:store.studyGoals,studyTasks:store.studyTasks,dailyMemos:store.dailyMemos};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download='dear-my-diary-backup.json';anchor.click();URL.revokeObjectURL(url)}
 const importData=async(file?:File)=>{if(!file)return;try{await store.importData(JSON.parse(await file.text()));store.setToast('백업을 가져왔습니다.')}catch{store.setToast('올바른 DEAR MY DIARY 백업 파일이 아닙니다.')}}
 const lowContrast=contrastRatio(preferences.defaultTextColor,preferences.defaultBackgroundColor)<4.5
 return <section className="settings-page-new"><header><span>환경설정</span><h1>설정</h1><p>글씨와 색상, 플래너 표시 방식 및 데이터 저장 방식을 조절합니다.</p></header>
  <article className="settings-card"><h2>프로필</h2><div className="settings-form"><label>표시 이름<input value={store.profile.displayName} onChange={event=>void store.updateProfile({...store.profile,displayName:event.target.value})}/></label><label>사용자 이름<input value={store.profile.handle} onChange={event=>void store.updateProfile({...store.profile,handle:event.target.value})}/></label><label>시간대<select value={store.profile.timezone} onChange={event=>void store.updateProfile({...store.profile,timezone:event.target.value})}><option>Asia/Seoul</option><option>UTC</option><option>America/New_York</option><option>Europe/London</option></select></label><label>기본 일정 시간(분)<input type="number" min="15" step="15" value={store.profile.defaultEventDuration} onChange={event=>void store.updateProfile({...store.profile,defaultEventDuration:+event.target.value})}/></label></div></article>
  <article className="settings-card"><h2>글씨 크기</h2><p>앱 전체에 즉시 반영되며 새로고침 후에도 유지됩니다.</p><div className="settings-actions">{[['작게',90],['기본',100],['크게',115],['매우 크게',130]].map(([label,value])=><button className={preferences.fontScale===value?'purple-button':''} key={value} onClick={()=>patch({fontScale:Number(value)})}>{label} {value}%</button>)}<button onClick={()=>patch({fontScale:100})}>기본값으로 되돌리기</button></div><label className="range-setting">세부 조절 <strong>{preferences.fontScale}%</strong><input type="range" min="80" max="140" step="5" value={preferences.fontScale} onChange={event=>patch({fontScale:+event.target.value})}/></label>
  <h2 className="settings-subhead">영어 글씨 크기</h2><p>WEEK OF, 요일(Mon/Tue), 시간축(06:00), 달 이름 같은 영어 라벨의 크기입니다.</p><div className="settings-actions">{[['기본',100],['크게',140],['더 크게',170],['최대',200]].map(([label,value])=><button className={(preferences.englishFontScale??140)===value?'purple-button':''} key={value} onClick={()=>patch({englishFontScale:Number(value)})}>{label} {value}%</button>)}</div><label className="range-setting">세부 조절 <strong>{preferences.englishFontScale??140}%</strong><input type="range" min="80" max="200" step="5" value={preferences.englishFontScale??140} onChange={event=>patch({englishFontScale:+event.target.value})}/></label>
  <div className="settings-live-preview"><b>실시간 미리보기</b><span>오늘의 일정과 공부 계획을 차분하게 기록해 보세요. — WEEK OF · Mon 11 · 06:00</span><button>예시 버튼</button></div></article>
  <article className="settings-card"><h2>색상 및 테마</h2><div className="color-settings">{colorFields.map(([key,label])=><label key={key}>{label}<span><input type="color" value={String(preferences[key])} onChange={event=>patch({[key]:event.target.value})}/><input value={String(preferences[key])} maxLength={7} pattern="#[0-9a-fA-F]{6}" onChange={event=>/^#[0-9a-fA-F]{6}$/.test(event.target.value)&&patch({[key]:event.target.value})}/></span></label>)}</div><label className="switch-row"><input type="checkbox" checked={preferences.autoContrastEnabled} onChange={event=>patch({autoContrastEnabled:event.target.checked})}/>자동으로 읽기 쉬운 글씨 색 선택</label>{lowContrast&&<div className="contrast-warning">현재 기본 글씨와 배경의 대비가 낮습니다. WCAG AA 기준에는 4.5:1 이상을 권장합니다.</div>}<div className="theme-preview" style={{color:preferences.defaultTextColor,background:preferences.defaultBackgroundColor,borderColor:preferences.calendarLineColor}}><b style={{color:preferences.accentColor}}>색상 미리보기</b><span>본문과 보조 배경, 달력 선이 이 모습으로 표시됩니다.</span></div><button onClick={()=>patch({...DEFAULT_PREFERENCES,fontScale:preferences.fontScale})}>색상 기본값 복원</button></article>
  <article className="settings-card"><h2>플래너 표시 분량</h2><div className="settings-actions">{([['여유롭게','relaxed'],['기본','default'],['촘촘하게','compact'],['사용자 지정','custom']] as const).map(([label,value])=><button className={preferences.plannerDensity===value?'purple-button':''} onClick={()=>density(value)} key={value}>{label}</button>)}</div><div className="settings-form compact-fields"><label>Monthly 일반 일정 수<input type="number" min="1" max="12" value={preferences.monthlyVisibleEventCount} onChange={event=>patch({plannerDensity:'custom',monthlyVisibleEventCount:+event.target.value})}/></label><label>Monthly 학습 항목 수<input type="number" min="1" max="12" value={preferences.monthlyVisibleTaskCount} onChange={event=>patch({plannerDensity:'custom',monthlyVisibleTaskCount:+event.target.value})}/></label><label>Weekly 체크리스트 수<input type="number" min="3" max="30" value={preferences.weeklyVisibleTaskCount} onChange={event=>patch({plannerDensity:'custom',weeklyVisibleTaskCount:+event.target.value})}/></label><label>날짜 칸 최소 높이<input type="number" min="90" max="260" value={preferences.calendarCellHeight} onChange={event=>patch({plannerDensity:'custom',calendarCellHeight:+event.target.value})}/></label><label>일정 카드 간격<input type="number" min="0" max="16" value={preferences.eventCardGap} onChange={event=>patch({plannerDensity:'custom',eventCardGap:+event.target.value})}/></label><label>체크리스트 행 높이<input type="number" min="24" max="64" value={preferences.checklistRowHeight} onChange={event=>patch({plannerDensity:'custom',checklistRowHeight:+event.target.value})}/></label><label>일정 제목 최대 줄 수<input type="number" min="1" max="3" value={preferences.eventTitleMaxLines} onChange={event=>patch({eventTitleMaxLines:+event.target.value})}/></label><label>완료 항목 최대 표시 수<input type="number" min="0" max="30" value={preferences.completedTaskLimit} onChange={event=>patch({completedTaskLimit:+event.target.value})}/></label><label>메모 영역 높이<input type="number" min="32" max="160" value={preferences.memoSectionHeight} onChange={event=>patch({memoSectionHeight:+event.target.value})}/></label></div><label className="switch-row"><input type="checkbox" checked={preferences.memoSectionEnabled} onChange={event=>patch({memoSectionEnabled:event.target.checked})}/>날짜별 메모 영역 표시</label><label className="switch-row"><input type="checkbox" checked={preferences.collapseCompletedTasks} onChange={event=>patch({collapseCompletedTasks:event.target.checked})}/>완료 항목 자동 접기</label></article>
  <article className="settings-card"><h2>체크리스트 및 자동 이월</h2><label>미완료 항목 정책<select value={preferences.rolloverPolicy} onChange={event=>patch({rolloverPolicy:event.target.value as UserPreferences['rolloverPolicy']})}><option value="none">자동 이월하지 않음</option><option value="next-day">다음 가능한 날로 이동</option><option value="reschedule">남은 전체 계획 다시 배분</option><option value="ask">매번 물어보기</option></select></label><label className="switch-row"><input type="checkbox" checked={preferences.keepLockedTasksOnReschedule} onChange={event=>patch({keepLockedTasksOnReschedule:event.target.checked})}/>재배분 시 고정 작업 유지</label></article>
  <article className="settings-card"><h2>접근성 및 단축키</h2><label className="switch-row"><input type="checkbox" checked={reduced} onChange={event=>{setReduced(event.target.checked);localStorage.setItem('dmd-reduced-motion',event.target.checked?'1':'0');document.documentElement.classList.toggle('reduced-motion',event.target.checked)}}/>움직임 줄이기</label><div className="shortcut-list"><span>선택한 일정의 Diary 열기</span><kbd>Alt / Option + 7</kbd><span>Brainstorm 메모 추가</span><kbd>N</kbd><span>캔버스 실행 취소/다시 실행</span><kbd>Ctrl / Cmd + Z</kbd></div></article>
  <article className="settings-card"><h2>DEMO_MODE 및 데이터</h2><p>외부 서비스가 설정되지 않은 경우에도 현재 브라우저에 모든 핵심 데이터를 저장합니다.</p><div className="settings-actions"><button onClick={()=>void store.loadSample()}>샘플 데이터 불러오기</button><button onClick={exportData}>백업 내보내기</button><button onClick={()=>fileRef.current?.click()}>백업 가져오기</button><input ref={fileRef} hidden type="file" accept="application/json" onChange={event=>void importData(event.target.files?.[0])}/><button className="danger-button" onClick={()=>{if(confirm('모든 일정, 다이어리, 댓글, 보드와 학습 목표를 초기화할까요?'))void store.reset()}}>전체 데이터 초기화</button></div></article>
 </section>
}
