import { useMemo, useState } from 'react'
import { format, isSameMonth, isToday } from 'date-fns'
import { EventEditor } from '../components/EventEditor'
import { eventOnDate, monthGrid, monthNameSpaced, moveMonth, toDateKey } from '../utils/dates'
import { newEvent, useDiaryStore } from '../store'
import type { PlannerEvent, StudyTask } from '../types'

const weekdays=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
export function MonthlyPage({anchor,setAnchor,openDiary}:{anchor:Date;setAnchor(date:Date):void;openDiary(id:string):void}){
 const store=useDiaryStore(),[editing,setEditing]=useState<PlannerEvent>();const dates=useMemo(()=>monthGrid(anchor),[anchor]);const active=store.events.filter(event=>!event.deletedAt);const tasks=store.studyTasks.filter(task=>!task.deletedAt);const goals=store.studyGoals.filter(goal=>!goal.deletedAt)
 const create=(date:Date)=>{const draft=newEvent(date),start=new Date(draft.startAt);start.setFullYear(date.getFullYear(),date.getMonth(),date.getDate());draft.startAt=start.toISOString();draft.endAt=new Date(start.getTime()+3600000).toISOString();setEditing(draft)}
 const toggleTask=(task:StudyTask)=>void store.updateStudyTask({...task,completedAmount:task.status==='completed'?0:task.plannedAmount,status:task.status==='completed'?'planned':'completed',completedAt:task.status==='completed'?undefined:new Date().toISOString(),updatedAt:new Date().toISOString()})
 const maxEvents=Math.max(1,store.preferences.monthlyVisibleEventCount-(store.preferences.fontScale>=125?2:store.preferences.fontScale>=115?1:0)),maxTasks=Math.max(1,store.preferences.monthlyVisibleTaskCount-(store.preferences.fontScale>=125?1:0))
 return <section className="planner-page monthly-page" style={{'--event-title-lines':store.preferences.eventTitleMaxLines} as React.CSSProperties}><div className="planner-heading"><div><span className="month-capsule">{monthNameSpaced(anchor)}</span><strong>{format(anchor,'yyyy')}</strong></div><div><button onClick={()=>setAnchor(moveMonth(anchor,-1))}>‹ Previous</button><button onClick={()=>setAnchor(new Date())}>Today</button><button onClick={()=>setAnchor(moveMonth(anchor,1))}>Next ›</button></div></div>
  <div className="calendar-grid weekday-row">{weekdays.map(day=><div key={day}>{day}</div>)}</div><div className="calendar-grid month-cells">{dates.map(date=>{const key=toDateKey(date),dayEvents=active.filter(event=>eventOnDate(event.startAt,date)),dayTasks=tasks.filter(task=>task.scheduledDate===key);const hidden=Math.max(0,dayEvents.length-maxEvents)+Math.max(0,dayTasks.length-maxTasks);return <div key={key} className={`month-cell ${!isSameMonth(date,anchor)?'outside':''} ${isToday(date)?'today':''}`} onDoubleClick={()=>create(date)} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();void store.moveEvent(event.dataTransfer.getData('text/event-id'),key)}}><button className="date-number" onClick={()=>create(date)} aria-label={`${format(date,'MMMM d')} 일정 만들기`}>{format(date,'d')}</button><div className="cell-events">{dayEvents.slice(0,maxEvents).map(event=><button draggable title={event.title} onDragStart={drag=>drag.dataTransfer.setData('text/event-id',event.id)} onClick={click=>{click.stopPropagation();store.selectEvent(event.id)}} onDoubleClick={click=>{click.stopPropagation();setEditing(event)}} onContextMenu={click=>{click.preventDefault();store.selectEvent(event.id);openDiary(event.id)}} className={`calendar-event ${store.selectedEventId===event.id?'selected':''}`} style={{'--event-color':event.borderColor??event.color,color:event.textColor,background:event.backgroundColor} as React.CSSProperties} key={event.id}><time>{event.allDay?'All day':format(new Date(event.startAt),'HH:mm')}</time><span>{event.title}</span><em>{event.status==='done'?'✓':''}</em></button>)}</div><div className="monthly-study-list">{dayTasks.slice(0,maxTasks).map(task=>{const goal=goals.find(value=>value.id===task.goalId);return <button title={task.title} className={`monthly-study-item ${task.status}`} style={{'--task-text':task.textColor,'--task-bg':task.backgroundColor,'--task-border':task.borderColor} as React.CSSProperties} key={task.id} onClick={click=>{click.stopPropagation();toggleTask(task)}}><span>{task.status==='completed'?'✓':'□'}</span><span>{goal?.subject??''} {task.startAmount}~{task.endAmount}{goal?.unitType==='problem'?'번':goal?.unitType==='lecture'?'강':'쪽'}</span></button>})}</div>{hidden>0&&<button className="more-events" title="숨겨진 항목 보기">+{hidden}개 더보기</button>}</div>})}</div>
  {store.selectedEventId&&<div className="selection-bar"><span>일정 선택됨</span><button onClick={()=>setEditing(active.find(event=>event.id===store.selectedEventId))}>수정</button><button onClick={()=>openDiary(store.selectedEventId!)}>Diary 열기 <kbd>Alt + 7</kbd></button></div>}
  {editing&&<EventEditor event={editing} onClose={()=>setEditing(undefined)} onSave={async event=>{await store.saveEvent(event);store.selectEvent(event.id);setEditing(undefined)}} onDelete={eventsHas(active,editing.id)?()=>{if(confirm('이 일정을 삭제할까요?')){void store.softDeleteEvent(editing.id);setEditing(undefined)}}:undefined}/>}</section>
}
const eventsHas=(events:PlannerEvent[],id:string)=>events.some(event=>event.id===id)
