import { useEffect, useMemo, useState } from 'react'
import { format, isSameMonth, isToday } from 'date-fns'
import { EventEditor } from '../components/EventEditor'
import { Modal } from '../../components/Modal'
import { eventCoveredKeys, monthGrid, monthNameSpaced, moveMonth, toDateKey } from '../utils/dates'
import { isEditableTarget } from '../utils/shortcuts'
import { newEvent, useDiaryStore } from '../store'
import { QuickCapture } from '../components/QuickCapture'
import type { PlannerEvent, StudyTask } from '../types'

const weekdays=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
export function MonthlyPage({anchor,setAnchor,openDiary}:{anchor:Date;setAnchor(date:Date):void;openDiary(id:string):void}){
 const store=useDiaryStore(),[editing,setEditing]=useState<PlannerEvent>(),[selectedDate,setSelectedDate]=useState<string>(),[brainDate,setBrainDate]=useState<string>();const dates=useMemo(()=>monthGrid(anchor),[anchor]);const active=store.events.filter(event=>!event.deletedAt);const tasks=store.studyTasks.filter(task=>!task.deletedAt);const goals=store.studyGoals.filter(goal=>!goal.deletedAt)
 // 반복 일정(FREQ=…)과 여러 날 걸친 일정을 화면 범위에 맞춰 날짜별로 펼친다.
 const eventsByDay=new Map<string,PlannerEvent[]>();if(dates.length){const rStart=dates[0],rEnd=dates[dates.length-1];for(const ev of active)for(const k of eventCoveredKeys(ev,rStart,rEnd)){const arr=eventsByDay.get(k);arr?arr.push(ev):eventsByDay.set(k,[ev])}}
 const create=(date:Date)=>{const draft=newEvent(date),start=new Date(draft.startAt);start.setFullYear(date.getFullYear(),date.getMonth(),date.getDate());draft.startAt=start.toISOString();draft.endAt=new Date(start.getTime()+3600000).toISOString();setEditing(draft)}
 // Alt+7 on Monthly opens the selected date's diary. Capture phase
 // + stopImmediatePropagation so it pre-empts the global "open diary" shortcut.
 useEffect(()=>{const handler=(event:KeyboardEvent)=>{if(!(event.altKey&&event.code==='Digit7')||isEditableTarget(event.target))return;const eventDate=store.selectedEventId?active.find(item=>item.id===store.selectedEventId)?.startAt:undefined;const key=selectedDate||(eventDate?toDateKey(new Date(eventDate)):undefined);if(!key){store.setToast('먼저 날짜(또는 일정)를 선택한 뒤 Alt+7을 눌러 주세요.');return}event.preventDefault();event.stopImmediatePropagation();setBrainDate(key)};addEventListener('keydown',handler,true);return()=>removeEventListener('keydown',handler,true)},[selectedDate,store.selectedEventId,active])
 const brainTitle=brainDate?`${+brainDate.split('-')[1]}월 ${+brainDate.split('-')[2]}일 Diary`:''
 const toggleTask=(task:StudyTask)=>void store.updateStudyTask({...task,completedAmount:task.status==='completed'?0:task.plannedAmount,status:task.status==='completed'?'planned':'completed',completedAt:task.status==='completed'?undefined:new Date().toISOString(),updatedAt:new Date().toISOString()})
 const maxEvents=Math.max(1,store.preferences.monthlyVisibleEventCount-(store.preferences.fontScale>=125?2:store.preferences.fontScale>=115?1:0)),maxTasks=Math.max(1,store.preferences.monthlyVisibleTaskCount-(store.preferences.fontScale>=125?1:0))
 return <section className="planner-page monthly-page" style={{'--event-title-lines':store.preferences.eventTitleMaxLines} as React.CSSProperties}><div className="planner-heading"><div><span className="month-capsule">{monthNameSpaced(anchor)}</span><strong>{format(anchor,'yyyy')}</strong></div><div><QuickCapture/><button onClick={()=>setAnchor(moveMonth(anchor,-1))}>‹ Previous</button><button onClick={()=>setAnchor(new Date())}>Today</button><button onClick={()=>setAnchor(moveMonth(anchor,1))}>Next ›</button></div></div>
  <div className="calendar-grid weekday-row">{weekdays.map(day=><div key={day}>{day}</div>)}</div><div className="calendar-grid month-cells">{dates.map(date=>{const key=toDateKey(date),dayEvents=eventsByDay.get(key)??[],dayTasks=tasks.filter(task=>task.scheduledDate===key);const hidden=Math.max(0,dayEvents.length-maxEvents)+Math.max(0,dayTasks.length-maxTasks);return <div key={key} className={`month-cell ${!isSameMonth(date,anchor)?'outside':''} ${isToday(date)?'today':''} ${selectedDate===key?'selected-date':''}`} onDoubleClick={()=>create(date)} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();void store.moveEvent(event.dataTransfer.getData('text/event-id'),key)}}><button className="date-number" title="날짜 선택 (Alt+7로 브레인스토밍)" onClick={()=>setSelectedDate(selectedDate===key?undefined:key)} aria-label={`${format(date,'MMMM d')} 날짜 선택`}>{format(date,'d')}{store.dateDiaries[key]?.trim()?<i className="has-brainstorm" title="Diary 있음">✦</i>:null}</button><div className="cell-events">{dayEvents.slice(0,maxEvents).map(event=><button draggable title={event.title} onDragStart={drag=>drag.dataTransfer.setData('text/event-id',event.id)} onClick={click=>{click.stopPropagation();store.selectEvent(event.id)}} onDoubleClick={click=>{click.stopPropagation();setEditing(event)}} className={`calendar-event ${store.selectedEventId===event.id?'selected':''}`} style={{'--event-color':event.borderColor??event.color,color:event.textColor,background:event.backgroundColor} as React.CSSProperties} key={event.id}><time>{event.allDay?'All day':format(new Date(event.startAt),'HH:mm')}</time><span>{event.title}</span><em>{event.status==='done'?'✓':''}</em></button>)}</div><div className="monthly-study-list">{dayTasks.slice(0,maxTasks).map(task=>{const goal=goals.find(value=>value.id===task.goalId);return <button title={task.title} className={`monthly-study-item ${task.status}`} style={{'--task-text':task.textColor,'--task-bg':task.backgroundColor,'--task-border':task.borderColor} as React.CSSProperties} key={task.id} onClick={click=>{click.stopPropagation();toggleTask(task)}}><span>{task.status==='completed'?'✓':'□'}</span><span>{goal?.subject??''} {task.startAmount}~{task.endAmount}{goal?.unitType==='problem'?'번':goal?.unitType==='lecture'?'강':'쪽'}</span></button>})}</div>{hidden>0&&<button className="more-events" title="숨겨진 항목 보기">+{hidden}개 더보기</button>}</div>})}</div>
  {selectedDate&&<div className="selection-bar date-bar"><span>{+selectedDate.split('-')[1]}월 {+selectedDate.split('-')[2]}일</span><button className="purple-button" onClick={()=>setBrainDate(selectedDate)}>Diary <kbd>Alt+7</kbd></button></div>}
  {brainDate&&<Modal title={brainTitle} wide onClose={()=>setBrainDate(undefined)}><div className="date-diary"><textarea className="date-diary-text" value={store.dateDiaries[brainDate]??''} placeholder="이 날의 이야기, 생각, 계획… 무엇이든 자유롭게 적어 보세요." onChange={event=>void store.saveDateDiary(brainDate,event.target.value)}/><small className="date-diary-hint">자동 저장됩니다 · Brainstorm 탭의 Diary에서 날짜별로 모아볼 수 있어요</small></div></Modal>}
  {editing&&<EventEditor event={editing} onClose={()=>setEditing(undefined)} onSave={async event=>{await store.saveEvent(event);store.selectEvent(event.id);setEditing(undefined)}} onDelete={eventsHas(active,editing.id)?()=>{if(confirm('이 일정을 삭제할까요?')){void store.softDeleteEvent(editing.id);setEditing(undefined)}}:undefined}/>}</section>
}
const eventsHas=(events:PlannerEvent[],id:string)=>events.some(event=>event.id===id)
