import { useEffect, useMemo, useState } from 'react'
import { addDays, format, isSameDay } from 'date-fns'
import { EventEditor } from '../components/EventEditor'
import { Modal } from '../../components/Modal'
import { formatEventTime, startMonday, toDateKey, weekDates } from '../utils/dates'
import { newEvent, useDiaryStore } from '../store'
import type { PlannerEvent, StudyTask } from '../types'

const hours=Array.from({length:18},(_,index)=>index+6),now=()=>new Date().toISOString()
function TaskEditor({task,onClose}:{task:StudyTask;onClose():void}){const store=useDiaryStore(),[value,setValue]=useState(task);const goal=store.studyGoals.find(item=>item.id===value.goalId);const save=async()=>{const amount=Math.min(value.plannedAmount,Math.max(0,value.completedAmount));await store.updateStudyTask({...value,completedAmount:amount,status:amount===0?'planned':amount>=value.plannedAmount?'completed':'partial',completedAt:amount>=value.plannedAmount?now():undefined,updatedAt:now()});onClose()};return <Modal title="학습 체크리스트 수정" onClose={onClose}><div className="study-form"><label>과목<select value={value.goalId} onChange={event=>setValue({...value,goalId:event.target.value})}>{store.studyGoals.filter(item=>!item.deletedAt).map(item=><option key={item.id} value={item.id}>{item.subject} · {item.title}</option>)}</select></label><label>작업 제목<input value={value.title} onChange={event=>setValue({...value,title:event.target.value})}/></label><label>날짜<input type="date" value={value.scheduledDate} onChange={event=>setValue({...value,scheduledDate:event.target.value})}/></label><label>계획 분량<input type="number" min="1" value={value.plannedAmount} onChange={event=>setValue({...value,plannedAmount:+event.target.value})}/></label><label>완료 분량<input type="number" min="0" max={value.plannedAmount} value={value.completedAmount} onChange={event=>setValue({...value,completedAmount:+event.target.value})}/></label><label>예상 시간(분)<input type="number" min="0" value={value.estimatedMinutes} onChange={event=>setValue({...value,estimatedMinutes:+event.target.value})}/></label><label>우선순위<input readOnly value={goal?.priority??'-'}/></label><label>색상<div><input type="color" title="글씨 색" value={value.textColor} onChange={event=>setValue({...value,textColor:event.target.value})}/><input type="color" title="배경 색" value={value.backgroundColor} onChange={event=>setValue({...value,backgroundColor:event.target.value})}/><input type="color" title="테두리 색" value={value.borderColor} onChange={event=>setValue({...value,borderColor:event.target.value})}/></div></label><label className="full">메모<textarea rows={3} value={value.notes} onChange={event=>setValue({...value,notes:event.target.value})}/></label><label className="inline"><input type="checkbox" checked={value.isLocked} onChange={event=>setValue({...value,isLocked:event.target.checked})}/>고정 작업</label></div><footer className="modal-actions"><button className="danger-button" onClick={async()=>{await store.updateStudyTask({...value,deletedAt:now(),updatedAt:now()});onClose()}}>삭제</button><span className="action-spacer"/><button onClick={onClose}>취소</button><button className="purple-button" onClick={save}>변경 사항 저장</button></footer></Modal>}

export function WeeklyPage({anchor,setAnchor,openDiary}:{anchor:Date;setAnchor(date:Date):void;openDiary(id:string):void}){
 const store=useDiaryStore(),[editing,setEditing]=useState<PlannerEvent>(),[editingTask,setEditingTask]=useState<StudyTask>(),[incompleteOnly,setIncompleteOnly]=useState(false),[subject,setSubject]=useState('all');const dates=useMemo(()=>weekDates(anchor),[anchor]),active=store.events.filter(event=>!event.deletedAt),goals=store.studyGoals.filter(goal=>!goal.deletedAt)
 useEffect(()=>{void store.rolloverOverdueTasks()},[])
 const resize=(event:PlannerEvent,delta:number)=>void store.saveEvent({...event,endAt:new Date(new Date(event.endAt).getTime()+delta*60000).toISOString(),updatedAt:now(),syncStatus:event.googleSync?'pending':'local'})
 const filtered=store.studyTasks.filter(task=>!task.deletedAt&&(!incompleteOnly||task.status!=='completed')&&(subject==='all'||task.goalId===subject)&&(!store.preferences.collapseCompletedTasks||task.status!=='completed'))
 const toggle=(task:StudyTask)=>void store.updateStudyTask({...task,completedAmount:task.status==='completed'?0:task.plannedAmount,status:task.status==='completed'?'planned':'completed',completedAt:task.status==='completed'?undefined:now(),updatedAt:now()})
 const addManual=(date:string)=>{const goal=goals[0];if(!goal){store.setToast('먼저 전체 공부 분량에서 목표를 추가해 주세요.');return}setEditingTask({id:crypto.randomUUID(),goalId:goal.id,scheduledDate:date,title:`${goal.subject} 직접 학습`,startAmount:0,endAmount:0,plannedAmount:1,completedAmount:0,estimatedMinutes:goal.estimatedMinutesPerUnit??0,status:'planned',isLocked:false,sortOrder:filtered.filter(task=>task.scheduledDate===date).length,textColor:goal.textColor,backgroundColor:goal.backgroundColor,borderColor:goal.borderColor,notes:'',createdAt:now(),updatedAt:now(),isAutoGenerated:false})}
 return <section className="planner-page weekly-page-new"><div className="planner-heading"><div><span className="week-label">WEEK OF</span><strong>{format(startMonday(anchor),'MMM d')} — {format(addDays(startMonday(anchor),6),'MMM d, yyyy')}</strong></div><div><button onClick={()=>setAnchor(addDays(anchor,-7))}>‹ Previous</button><button onClick={()=>setAnchor(new Date())}>This Week</button><button onClick={()=>setAnchor(addDays(anchor,7))}>Next ›</button></div></div>
  <div className="study-toolbar"><div><label><input type="checkbox" checked={incompleteOnly} onChange={event=>setIncompleteOnly(event.target.checked)}/> 미완료만 보기</label><select value={subject} onChange={event=>setSubject(event.target.value)}><option value="all">모든 과목</option>{goals.map(goal=><option key={goal.id} value={goal.id}>{goal.subject}</option>)}</select></div><button onClick={()=>{const weekIds=new Set(dates.map(toDateKey));filtered.filter(task=>weekIds.has(task.scheduledDate)).forEach(task=>{if(task.status!=='completed')void store.updateStudyTask({...task,completedAmount:task.plannedAmount,status:'completed',completedAt:now(),updatedAt:now()})})}}>이번 주 일괄 완료</button></div>
  <div className="weekly-study-board">{dates.map(date=>{const key=toDateKey(date),dayTasks=filtered.filter(task=>task.scheduledDate===key).slice(0,store.preferences.weeklyVisibleTaskCount);return <div className="weekly-study-day" key={key} onDragOver={event=>event.preventDefault()} onDrop={event=>{const id=event.dataTransfer.getData('text/study-task');const task=store.studyTasks.find(item=>item.id===id);if(task&&!task.isLocked)void store.updateStudyTask({...task,scheduledDate:key,updatedAt:now()})}}><header><b>{format(date,'EEE d')}</b><button title="직접 체크리스트 추가" onClick={()=>addManual(key)}>＋</button></header><div className="weekly-study-list">{dayTasks.map(task=><div draggable={!task.isLocked} onDragStart={event=>event.dataTransfer.setData('text/study-task',task.id)} className={`study-check-row ${task.status}`} key={task.id} style={{'--task-text':task.textColor,'--task-bg':task.backgroundColor,'--task-border':task.borderColor} as React.CSSProperties}><input type="checkbox" checked={task.status==='completed'} aria-label={`${task.title} 완료`} onChange={()=>toggle(task)}/><button className="study-task-title" title={task.title} onClick={()=>setEditingTask(task)}><b>{task.title}</b><small>{task.completedAmount}/{task.plannedAmount} · {task.estimatedMinutes}분 · {task.isAutoGenerated?'자동':'직접'}{task.isLocked?' · 고정':''}</small></button><button title="수정" onClick={()=>setEditingTask(task)}>⋯</button></div>)}{filtered.filter(task=>task.scheduledDate===key).length>dayTasks.length&&<button className="more-events">+{filtered.filter(task=>task.scheduledDate===key).length-dayTasks.length}개 더보기</button>}</div>{store.preferences.memoSectionEnabled&&<textarea className="daily-memo" aria-label={`${format(date,'M월 d일')} 메모`} style={{height:'var(--memo-height)'}} value={store.dailyMemos[key]??''} placeholder="짧은 메모" onChange={event=>void store.saveDailyMemo(key,event.target.value)}/>}</div>})}</div>
  <div className="all-day-grid"><div>ALL-DAY</div>{dates.map(date=><div key={date.toISOString()}>{active.filter(event=>event.allDay&&isSameDay(new Date(event.startAt),date)).map(event=><button key={event.id} style={{borderColor:event.borderColor??event.color,color:event.textColor,background:event.backgroundColor}} onClick={()=>{store.selectEvent(event.id);setEditing(event)}}>{event.title}</button>)}</div>)}</div>
  <div className="week-timeline"><div className="time-axis">{hours.map(hour=><div key={hour}>{String(hour).padStart(2,'0')}:00</div>)}</div>{dates.map(date=><div className={`week-day ${isSameDay(date,new Date())?'today':''}`} key={date.toISOString()} onDoubleClick={event=>{const draft=newEvent(date),rect=event.currentTarget.getBoundingClientRect(),hour=6+Math.max(0,Math.min(17,Math.floor((event.clientY-rect.top)/60))),start=new Date(date);start.setHours(hour,0,0,0);draft.startAt=start.toISOString();draft.endAt=new Date(start.getTime()+3600000).toISOString();setEditing(draft)}} onDragOver={event=>event.preventDefault()} onDrop={event=>void store.moveEvent(event.dataTransfer.getData('text/event-id'),toDateKey(date))}><header><span>{format(date,'EEE')}</span><b>{format(date,'d')}</b></header>{hours.map(hour=><div className="hour-line" key={hour}/>)}{active.filter(event=>!event.allDay&&isSameDay(new Date(event.startAt),date)).map((event,index)=>{const start=new Date(event.startAt),duration=Math.max(30,(new Date(event.endAt).getTime()-start.getTime())/60000);return <button draggable title={event.title} onDragStart={drag=>drag.dataTransfer.setData('text/event-id',event.id)} key={event.id} className={`timeline-event ${store.selectedEventId===event.id?'selected':''}`} style={{top:52+(start.getHours()-6)*60+start.getMinutes(),height:Math.max(28,duration),background:event.backgroundColor??event.color,color:event.textColor,borderColor:event.borderColor,left:index%2?'50%':'2%',width:index%2?'48%':'96%'}} onClick={()=>store.selectEvent(event.id)} onDoubleClick={()=>setEditing(event)}><b>{event.title}</b><span>{formatEventTime(event.startAt)}</span><i onClick={click=>{click.stopPropagation();resize(event,30)}} title="30분 늘리기">＋</i></button>})}{isSameDay(date,new Date())&&<div className="now-line" style={{top:52+(new Date().getHours()-6)*60+new Date().getMinutes()}}/>}</div>)}</div>
  {store.selectedEventId&&<div className="selection-bar"><span>일정 선택됨</span><button onClick={()=>setEditing(active.find(event=>event.id===store.selectedEventId))}>수정</button><button onClick={()=>openDiary(store.selectedEventId!)}>이 일정 기록하기 <kbd>Alt + 7</kbd></button></div>}
  {editingTask&&<TaskEditor task={editingTask} onClose={()=>setEditingTask(undefined)}/>} {editing&&<EventEditor event={editing} onClose={()=>setEditing(undefined)} onSave={async event=>{await store.saveEvent(event);store.selectEvent(event.id);setEditing(undefined)}} onDelete={active.some(event=>event.id===editing.id)?()=>{if(confirm('이 일정을 삭제할까요?')){void store.softDeleteEvent(editing.id);setEditing(undefined)}}:undefined}/>}</section>
}
