import { useEffect, useMemo, useState } from 'react'
import { addDays, format, isSameDay } from 'date-fns'
import { EventEditor } from '../components/EventEditor'
import { Modal } from '../../components/Modal'
import { formatEventTime, occursStartingOn, startMonday, toDateKey, weekDates } from '../utils/dates'
import { newEvent, useDiaryStore } from '../store'
import { QuickCapture } from '../components/QuickCapture'
import type { PlannerEvent, StudyTask } from '../types'

const hours=Array.from({length:18},(_,index)=>index+6),now=()=>new Date().toISOString()
const DEFAULT_STUDY_START=18*60 // 시간 미입력 시 자동 배치 시작(오후 6시)
const toMin=(t?:string):number|null=>{if(!t||!/^\d{1,2}:\d{2}$/.test(t))return null;const [h,m]=t.split(':').map(Number);return h*60+m}
const fmtMin=(m:number)=>`${String(Math.floor(m/60)%24).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`
// 겹치지 않는 항목은 칸을 꽉 채우고(col 1개), 시간이 겹치는 항목만 나란히 나눠 배치.
function layoutDay(items:any[]):any[]{
 const sorted=[...items].sort((a,b)=>a.start-b.start||a.end-b.end)
 let group:any[]=[],clusterEnd=-1
 const flush=()=>{const colEnds:number[]=[];for(const it of group){let c=colEnds.findIndex(end=>end<=it.start);if(c===-1){c=colEnds.length;colEnds.push(it.end)}else colEnds[c]=it.end;it.col=c}for(const it of group)it.cols=colEnds.length;group=[]}
 for(const it of sorted){if(group.length&&it.start>=clusterEnd){flush();clusterEnd=-1}group.push(it);clusterEnd=Math.max(clusterEnd,it.end)}
 if(group.length)flush()
 return sorted
}

function TaskEditor({task,onClose}:{task:StudyTask;onClose():void}){const store=useDiaryStore(),[value,setValue]=useState(task);const goal=store.studyGoals.find(item=>item.id===value.goalId);const save=async()=>{const amount=Math.min(value.plannedAmount,Math.max(0,value.completedAmount));await store.updateStudyTask({...value,completedAmount:amount,status:amount===0?'planned':amount>=value.plannedAmount?'completed':'partial',completedAt:amount>=value.plannedAmount?now():undefined,updatedAt:now()});onClose()};return <Modal title="학습 체크리스트 수정" onClose={onClose}><div className="study-form"><label>과목<select value={value.goalId} onChange={event=>setValue({...value,goalId:event.target.value})}>{store.studyGoals.filter(item=>!item.deletedAt).map(item=><option key={item.id} value={item.id}>{item.subject} · {item.title}</option>)}</select></label><label>작업 제목<input value={value.title} onChange={event=>setValue({...value,title:event.target.value})}/></label><label>날짜<input type="date" value={value.scheduledDate} onChange={event=>setValue({...value,scheduledDate:event.target.value})}/></label><label>시작 시간<input type="time" value={value.startTime??''} onChange={event=>setValue({...value,startTime:event.target.value||undefined})}/><small>비우면 시간표에 자동 배치</small></label><label>계획 분량<input type="number" min="1" value={value.plannedAmount} onChange={event=>setValue({...value,plannedAmount:+event.target.value})}/></label><label>완료 분량<input type="number" min="0" max={value.plannedAmount} value={value.completedAmount} onChange={event=>setValue({...value,completedAmount:+event.target.value})}/></label><label>예상 시간(분)<input type="number" min="0" value={value.estimatedMinutes} onChange={event=>setValue({...value,estimatedMinutes:+event.target.value})}/></label><label>우선순위<input readOnly value={goal?.priority??'-'}/></label><label>색상<div><input type="color" title="글씨 색" value={value.textColor} onChange={event=>setValue({...value,textColor:event.target.value})}/><input type="color" title="배경 색" value={value.backgroundColor} onChange={event=>setValue({...value,backgroundColor:event.target.value})}/><input type="color" title="테두리 색" value={value.borderColor} onChange={event=>setValue({...value,borderColor:event.target.value})}/></div></label><label className="full">메모<textarea rows={3} value={value.notes} onChange={event=>setValue({...value,notes:event.target.value})}/></label><label className="inline"><input type="checkbox" checked={value.isLocked} onChange={event=>setValue({...value,isLocked:event.target.checked})}/>고정 작업</label></div><footer className="modal-actions"><button className="danger-button" onClick={async()=>{await store.updateStudyTask({...value,deletedAt:now(),updatedAt:now()});onClose()}}>삭제</button><span className="action-spacer"/><button onClick={onClose}>취소</button><button className="purple-button" onClick={save}>변경 사항 저장</button></footer></Modal>}

export function WeeklyPage({anchor,setAnchor,openDiary}:{anchor:Date;setAnchor(date:Date):void;openDiary(id:string):void}){
 const store=useDiaryStore(),[editing,setEditing]=useState<PlannerEvent>(),[editingTask,setEditingTask]=useState<StudyTask>(),[incompleteOnly,setIncompleteOnly]=useState(false),[subject,setSubject]=useState('all');const dates=useMemo(()=>weekDates(anchor),[anchor]),active=store.events.filter(event=>!event.deletedAt),goals=store.studyGoals.filter(goal=>!goal.deletedAt)
 useEffect(()=>{void store.rolloverOverdueTasks()},[])
 const resize=(event:PlannerEvent,delta:number)=>void store.saveEvent({...event,endAt:new Date(new Date(event.endAt).getTime()+delta*60000).toISOString(),updatedAt:now(),syncStatus:event.googleSync?'pending':'local'})
 const filtered=store.studyTasks.filter(task=>!task.deletedAt&&(!incompleteOnly||task.status!=='completed')&&(subject==='all'||task.goalId===subject))
 const toggle=(task:StudyTask)=>void store.updateStudyTask({...task,completedAmount:task.status==='completed'?0:task.plannedAmount,status:task.status==='completed'?'planned':'completed',completedAt:task.status==='completed'?undefined:now(),updatedAt:now()})
 const toggleEvent=(event:PlannerEvent)=>void store.saveEvent({...event,status:event.status==='done'?'planned':'done',updatedAt:now(),syncStatus:event.googleSync?'pending':'local'})
 // 학습 태스크를 시간표에 자동 배치. 지정 시간(미입력 시 오후 6시)부터 예상 시간만큼 순서대로 쌓는다.
 const studyBlocks=(key:string)=>{
  const rows=filtered.filter(task=>task.scheduledDate===key).map(task=>({task,goal:goals.find(g=>g.id===task.goalId)}))
  const out:any[]=[]
  const clamp=(s:number,e:number)=>({start:s,end:Math.max(s+15,Math.min(e,24*60))})
  // 1) 태스크에 시각이 지정된 경우(드래그/직접 입력) → 그 시각 고정
  const rest:typeof rows=[]
  for(const r of rows){const fixed=toMin(r.task.startTime);if(fixed!=null){const dur=r.task.estimatedMinutes>0?r.task.estimatedMinutes:60;out.push({...r,...clamp(fixed,fixed+dur),auto:false})}else rest.push(r)}
  // 2) 목표에 공부 시간대가 지정된 태스크 → 그 시간대에 배치(같은 목표끼리는 이어서)
  const goalCursor:Record<string,number>={}
  for(const r of rest.filter(r=>toMin(r.goal?.dailyStartTime)!=null)){const win=toMin(r.goal!.dailyStartTime)!,winEnd=toMin(r.goal?.dailyEndTime);const start=Math.max(win,goalCursor[r.goal!.id]??win),dur=r.task.estimatedMinutes>0?r.task.estimatedMinutes:60;let end=start+dur;if(winEnd&&winEnd>start&&end>winEnd)end=winEnd;goalCursor[r.goal!.id]=end;out.push({...r,...clamp(start,end),auto:false})}
  // 3) 나머지는 오후 6시부터 순서대로 자동 배치(겹치면 나란히 표시)
  let cursor=DEFAULT_STUDY_START
  for(const r of rest.filter(r=>toMin(r.goal?.dailyStartTime)==null).sort((a,b)=>(a.goal?.subject??'').localeCompare(b.goal?.subject??''))){const dur=r.task.estimatedMinutes>0?r.task.estimatedMinutes:60;out.push({...r,...clamp(cursor,cursor+dur),auto:true});cursor=Math.min(cursor+dur,23*60)}
  return out
 }
 return <section className="planner-page weekly-page-new"><div className="planner-heading"><div><span className="week-label">WEEK OF</span><strong>{format(startMonday(anchor),'MMM d')} — {format(addDays(startMonday(anchor),6),'MMM d, yyyy')}</strong></div><div><QuickCapture/><button onClick={()=>setAnchor(addDays(anchor,-7))}>‹ Previous</button><button onClick={()=>setAnchor(new Date())}>This Week</button><button onClick={()=>setAnchor(addDays(anchor,7))}>Next ›</button></div></div>
  <div className="study-toolbar"><div><label><input type="checkbox" checked={incompleteOnly} onChange={event=>setIncompleteOnly(event.target.checked)}/> 미완료만 보기</label><select value={subject} onChange={event=>setSubject(event.target.value)}><option value="all">모든 과목</option>{goals.map(goal=><option key={goal.id} value={goal.id}>{goal.subject}</option>)}</select></div><button onClick={()=>{const weekIds=new Set(dates.map(toDateKey));filtered.filter(task=>weekIds.has(task.scheduledDate)).forEach(task=>{if(task.status!=='completed')void store.updateStudyTask({...task,completedAmount:task.plannedAmount,status:'completed',completedAt:now(),updatedAt:now()})})}}>이번 주 학습 일괄 완료</button></div>
  <div className="weekly-memo-board">{dates.map(date=>{const key=toDateKey(date);return <div className="weekly-memo-day" key={key}><header><b>{format(date,'EEE d')}</b></header><textarea className="daily-memo" aria-label={`${format(date,'M월 d일')} 메모`} value={store.dailyMemos[key]??''} placeholder="짧은 메모" onChange={event=>void store.saveDailyMemo(key,event.target.value)}/></div>})}</div>
  <div className="all-day-grid"><div>ALL-DAY</div>{dates.map(date=><div key={date.toISOString()}>{active.filter(event=>event.allDay&&occursStartingOn(event,date)).map(event=><span key={event.id} className={`allday-event ${event.status==='done'?'done':''}`} style={{borderColor:event.borderColor??event.color,color:event.textColor,background:event.backgroundColor}}><input type="checkbox" className="event-check" checked={event.status==='done'} onChange={()=>toggleEvent(event)} aria-label={`${event.title} 완료`}/><button onClick={()=>{store.selectEvent(event.id);setEditing(event)}}>{event.title}</button></span>)}</div>)}</div>
  <div className="week-timeline"><div className="time-axis">{hours.map(hour=><div key={hour}>{String(hour).padStart(2,'0')}:00</div>)}</div>{dates.map(date=>{const key=toDateKey(date);const evItems=active.filter(event=>!event.allDay&&occursStartingOn(event,date)).map(event=>{const s=new Date(event.startAt),start=s.getHours()*60+s.getMinutes();return {kind:'event',event,start,end:start+Math.max(30,(new Date(event.endAt).getTime()-s.getTime())/60000)}});const stItems=studyBlocks(key).map(b=>({kind:'study',task:b.task,goal:b.goal,start:b.start,end:b.end,auto:b.auto}));const items=layoutDay([...evItems,...stItems]);return <div className={`week-day ${isSameDay(date,new Date())?'today':''}`} key={date.toISOString()} onDoubleClick={event=>{const draft=newEvent(date),rect=event.currentTarget.getBoundingClientRect(),hour=6+Math.max(0,Math.min(17,Math.floor((event.clientY-rect.top)/60))),start=new Date(date);start.setHours(hour,0,0,0);draft.startAt=start.toISOString();draft.endAt=new Date(start.getTime()+3600000).toISOString();setEditing(draft)}} onDragOver={event=>event.preventDefault()} onDrop={event=>{const evId=event.dataTransfer.getData('text/event-id');if(evId){void store.moveEvent(evId,toDateKey(date));return}const stId=event.dataTransfer.getData('text/study-id');if(!stId)return;const task=store.studyTasks.find(item=>item.id===stId);if(!task)return;const rect=event.currentTarget.getBoundingClientRect(),min=Math.max(360,Math.min(23*60,360+Math.round((event.clientY-rect.top-52)/15)*15));void store.updateStudyTask({...task,scheduledDate:toDateKey(date),startTime:fmtMin(min),updatedAt:now()})}}><header><span>{format(date,'EEE')}</span><b>{format(date,'d')}</b></header>{hours.map(hour=><div className="hour-line" key={hour}/>)}
   {items.map((it:any)=>{const leftPct=2+it.col*96/it.cols,widthPct=96/it.cols-1,top=52+(Math.max(it.start,360)-360);if(it.kind==='event'){const event:PlannerEvent=it.event;return <button draggable title={event.title} onDragStart={drag=>drag.dataTransfer.setData('text/event-id',event.id)} key={event.id} className={`timeline-event ${store.selectedEventId===event.id?'selected':''} ${event.status==='done'?'done':''}`} style={{top,height:Math.max(28,it.end-it.start),background:event.backgroundColor??event.color,color:event.textColor,borderColor:event.borderColor,left:`${leftPct}%`,width:`${widthPct}%`}} onClick={()=>store.selectEvent(event.id)} onDoubleClick={click=>{click.stopPropagation();setEditing(event)}}><input type="checkbox" className="event-check" checked={event.status==='done'} onClick={click=>click.stopPropagation()} onChange={()=>toggleEvent(event)} aria-label={`${event.title} 완료`}/><b>{event.title}</b><span>{formatEventTime(event.startAt)}</span><i onClick={click=>{click.stopPropagation();resize(event,30)}} title="30분 늘리기">＋</i></button>}const task:StudyTask=it.task,goal=it.goal;return <button key={task.id} draggable onDragStart={drag=>{drag.stopPropagation();drag.dataTransfer.setData('text/study-id',task.id)}} title={`${goal?.subject??''} ${task.title} · 드래그해 시간 이동`} className={`timeline-study ${task.status==='completed'?'done':''} ${it.auto?'auto':''}`} style={{top,height:Math.max(24,it.end-it.start),left:`${leftPct}%`,width:`${widthPct}%`,'--task-text':task.textColor,'--task-bg':task.backgroundColor,'--task-border':task.borderColor} as React.CSSProperties} onClick={()=>setEditingTask(task)} onDoubleClick={click=>{click.stopPropagation();setEditingTask(task)}}><input type="checkbox" className="event-check" checked={task.status==='completed'} onClick={click=>click.stopPropagation()} onChange={()=>toggle(task)} aria-label={`${task.title} 완료`}/><b>{goal?.subject??'학습'}</b><span>{fmtMin(it.start)}~{fmtMin(it.end)}{it.auto?' · 자동':''}</span></button>})}
   {isSameDay(date,new Date())&&<div className="now-line" style={{top:52+(new Date().getHours()-6)*60+new Date().getMinutes()}}/>}</div>})}</div>
  {store.selectedEventId&&<div className="selection-bar"><span>일정 선택됨</span><button onClick={()=>setEditing(active.find(event=>event.id===store.selectedEventId))}>수정</button><button onClick={()=>openDiary(store.selectedEventId!)}>이 일정 기록하기 <kbd>Alt + 7</kbd></button></div>}
  {editingTask&&<TaskEditor task={editingTask} onClose={()=>setEditingTask(undefined)}/>} {editing&&<EventEditor event={editing} onClose={()=>setEditing(undefined)} onSave={async event=>{await store.saveEvent(event);store.selectEvent(event.id);setEditing(undefined)}} onDelete={active.some(event=>event.id===editing.id)?()=>{if(confirm('이 일정을 삭제할까요?')){void store.softDeleteEvent(editing.id);setEditing(undefined)}}:undefined}/>}</section>
}
