import type { DiaryData } from './types'
import { DEFAULT_DIARY_DATA } from './types'
import { isSupabaseConfigured, supabase } from '../lib/supabase'

const KEY = 'dear-my-diary-v1'
const cloneDefaults = (): DiaryData => structuredClone(DEFAULT_DIARY_DATA)
export interface DiaryRepository { load(): Promise<DiaryData>; save(data: DiaryData): Promise<void>; clear(): Promise<void> }

export const localDiaryRepository: DiaryRepository = {
  async load() { const raw=localStorage.getItem(KEY); if(!raw)return cloneDefaults(); try{return validateDiaryData(JSON.parse(raw))}catch{return cloneDefaults()} },
  async save(data) { localStorage.setItem(KEY, JSON.stringify(data)) },
  async clear() { localStorage.removeItem(KEY) }
}

export const DEMO_MODE = import.meta.env.NEXT_PUBLIC_DEMO_MODE === 'true' || !isSupabaseConfigured
const snakeEvent=(event:DiaryData['events'][number],userId:string)=>({id:event.id,user_id:userId,title:event.title,description:event.description,start_at:event.startAt,end_at:event.endAt,all_day:event.allDay,color:event.color,location:event.location,status:event.status,recurrence_rule:event.recurrenceRule,reminder_minutes:event.reminderMinutes,source:event.source,google_sync:event.googleSync,external_provider:event.externalProvider,external_calendar_id:event.externalCalendarId,external_event_id:event.externalEventId,external_updated_at:event.externalUpdatedAt,last_synced_at:event.lastSyncedAt,sync_status:event.syncStatus,sync_error:event.syncError,deleted_at:event.deletedAt,created_at:event.createdAt,updated_at:event.updatedAt,text_color:event.textColor,background_color:event.backgroundColor,border_color:event.borderColor})
const camelEvent=(row:Record<string,unknown>):DiaryData['events'][number]=>({id:String(row.id),title:String(row.title),description:String(row.description??''),startAt:String(row.start_at),endAt:String(row.end_at),allDay:Boolean(row.all_day),color:String(row.color),location:String(row.location??''),status:row.status as DiaryData['events'][number]['status'],recurrenceRule:String(row.recurrence_rule??''),reminderMinutes:row.reminder_minutes as number|undefined,source:row.source as 'local'|'google',googleSync:Boolean(row.google_sync),externalProvider:row.external_provider as string|undefined,externalCalendarId:row.external_calendar_id as string|undefined,externalEventId:row.external_event_id as string|undefined,externalUpdatedAt:row.external_updated_at as string|undefined,lastSyncedAt:row.last_synced_at as string|undefined,syncStatus:row.sync_status as DiaryData['events'][number]['syncStatus'],syncError:row.sync_error as string|undefined,deletedAt:row.deleted_at as string|undefined,createdAt:String(row.created_at),updatedAt:String(row.updated_at),textColor:row.text_color as string|undefined,backgroundColor:row.background_color as string|undefined,borderColor:row.border_color as string|undefined})
const snakePreferences=(p:DiaryData['preferences'],userId:string,calendar:DiaryData['calendar'],dailyMemos:DiaryData['dailyMemos'],dateBrainstorms:DiaryData['dateBrainstorms'])=>({user_id:userId,date_brainstorms:dateBrainstorms,font_scale:p.fontScale,planner_density:p.plannerDensity,monthly_visible_event_count:p.monthlyVisibleEventCount,monthly_visible_task_count:p.monthlyVisibleTaskCount,weekly_visible_task_count:p.weeklyVisibleTaskCount,calendar_cell_height:p.calendarCellHeight,event_card_gap:p.eventCardGap,checklist_row_height:p.checklistRowHeight,event_title_max_lines:p.eventTitleMaxLines,memo_section_enabled:p.memoSectionEnabled,memo_section_height:p.memoSectionHeight,collapse_completed_tasks:p.collapseCompletedTasks,completed_task_limit:p.completedTaskLimit,default_text_color:p.defaultTextColor,default_background_color:p.defaultBackgroundColor,secondary_background_color:p.secondaryBackgroundColor,accent_color:p.accentColor,calendar_line_color:p.calendarLineColor,completed_item_color:p.completedItemColor,selected_item_color:p.selectedItemColor,auto_contrast_enabled:p.autoContrastEnabled,default_buffer_days:p.defaultBufferDays,default_daily_study_minutes:p.defaultDailyStudyMinutes,default_study_weekdays:p.defaultStudyWeekdays,rollover_policy:p.rolloverPolicy,keep_locked_tasks_on_reschedule:p.keepLockedTasksOnReschedule,recent_colors:p.recentColors,calendar_options:calendar,daily_memos:dailyMemos,updated_at:new Date().toISOString()})
const camelPreferences=(row:any):DiaryData['preferences']=>({...DEFAULT_DIARY_DATA.preferences,fontScale:row.font_scale,plannerDensity:row.planner_density,monthlyVisibleEventCount:row.monthly_visible_event_count,monthlyVisibleTaskCount:row.monthly_visible_task_count,weeklyVisibleTaskCount:row.weekly_visible_task_count,calendarCellHeight:row.calendar_cell_height,eventCardGap:row.event_card_gap,checklistRowHeight:row.checklist_row_height,eventTitleMaxLines:row.event_title_max_lines,memoSectionEnabled:row.memo_section_enabled,memoSectionHeight:row.memo_section_height,collapseCompletedTasks:row.collapse_completed_tasks,completedTaskLimit:row.completed_task_limit,defaultTextColor:row.default_text_color,defaultBackgroundColor:row.default_background_color,secondaryBackgroundColor:row.secondary_background_color,accentColor:row.accent_color,calendarLineColor:row.calendar_line_color,completedItemColor:row.completed_item_color,selectedItemColor:row.selected_item_color,autoContrastEnabled:row.auto_contrast_enabled,defaultBufferDays:row.default_buffer_days,defaultDailyStudyMinutes:row.default_daily_study_minutes,defaultStudyWeekdays:row.default_study_weekdays??[1,2,3,4,5,6,0],rolloverPolicy:row.rollover_policy,keepLockedTasksOnReschedule:row.keep_locked_tasks_on_reschedule,recentColors:row.recent_colors??[]})
const snakeGoal=(goal:DiaryData['studyGoals'][number],user:string)=>({id:goal.id,user_id:user,subject:goal.subject,title:goal.title,unit_type:goal.unitType,custom_unit_label:goal.customUnitLabel,total_amount:goal.totalAmount,completed_amount:goal.completedAmount,start_date:goal.startDate,deadline:goal.deadline,priority:goal.priority,difficulty:goal.difficulty,min_daily_amount:goal.minDailyAmount,max_daily_amount:goal.maxDailyAmount,chunk_size:goal.chunkSize,available_weekdays:goal.availableWeekdays,excluded_dates:goal.excludedDates,rest_dates:goal.restDates,daily_capacity:goal.dailyCapacity,estimated_minutes_per_unit:goal.estimatedMinutesPerUnit,buffer_days:goal.bufferDays,text_color:goal.textColor,background_color:goal.backgroundColor,border_color:goal.borderColor,notes:goal.notes,auto_schedule_enabled:goal.autoScheduleEnabled,google_sync_enabled:goal.googleSyncEnabled,apple_feed_enabled:goal.appleFeedEnabled,status:goal.status,created_at:goal.createdAt,updated_at:goal.updatedAt,deleted_at:goal.deletedAt})
const camelGoal=(row:any):DiaryData['studyGoals'][number]=>({id:row.id,subject:row.subject,title:row.title,unitType:row.unit_type,customUnitLabel:row.custom_unit_label,totalAmount:+row.total_amount,completedAmount:+row.completed_amount,startDate:row.start_date,deadline:row.deadline,priority:row.priority,difficulty:row.difficulty,minDailyAmount:row.min_daily_amount==null?undefined:+row.min_daily_amount,maxDailyAmount:row.max_daily_amount==null?undefined:+row.max_daily_amount,chunkSize:+row.chunk_size,availableWeekdays:row.available_weekdays,excludedDates:row.excluded_dates??[],restDates:row.rest_dates??[],dailyCapacity:row.daily_capacity??{},estimatedMinutesPerUnit:row.estimated_minutes_per_unit==null?undefined:+row.estimated_minutes_per_unit,bufferDays:row.buffer_days,textColor:row.text_color,backgroundColor:row.background_color,borderColor:row.border_color,notes:row.notes,autoScheduleEnabled:row.auto_schedule_enabled,googleSyncEnabled:row.google_sync_enabled,appleFeedEnabled:row.apple_feed_enabled,status:row.status,createdAt:row.created_at,updatedAt:row.updated_at,deletedAt:row.deleted_at??undefined})
const snakeTask=(task:DiaryData['studyTasks'][number],user:string)=>({id:task.id,user_id:user,goal_id:task.goalId,scheduled_date:task.scheduledDate,title:task.title,start_amount:task.startAmount,end_amount:task.endAmount,planned_amount:task.plannedAmount,completed_amount:task.completedAmount,estimated_minutes:task.estimatedMinutes,status:task.status,is_locked:task.isLocked,is_auto_generated:task.isAutoGenerated,sort_order:task.sortOrder,text_color:task.textColor,background_color:task.backgroundColor,border_color:task.borderColor,notes:task.notes,completed_at:task.completedAt,external_provider:task.externalProvider,external_calendar_id:task.externalCalendarId,external_event_id:task.externalEventId,last_synced_at:task.lastSyncedAt,created_at:task.createdAt,updated_at:task.updatedAt,deleted_at:task.deletedAt})
const camelTask=(row:any):DiaryData['studyTasks'][number]=>({id:row.id,goalId:row.goal_id,scheduledDate:row.scheduled_date,title:row.title,startAmount:+row.start_amount,endAmount:+row.end_amount,plannedAmount:+row.planned_amount,completedAmount:+row.completed_amount,estimatedMinutes:+row.estimated_minutes,status:row.status,isLocked:row.is_locked,isAutoGenerated:row.is_auto_generated,sortOrder:row.sort_order,textColor:row.text_color,backgroundColor:row.background_color,borderColor:row.border_color,notes:row.notes,completedAt:row.completed_at??undefined,externalProvider:row.external_provider??undefined,externalCalendarId:row.external_calendar_id??undefined,externalEventId:row.external_event_id??undefined,lastSyncedAt:row.last_synced_at??undefined,createdAt:row.created_at,updatedAt:row.updated_at,deletedAt:row.deleted_at??undefined})

async function userId(){if(!supabase)throw new Error('Supabase is not configured');const {data:{user},error}=await supabase.auth.getUser();if(error||!user)throw new Error('Sign in to load your diary');return user.id}
async function removeMissing(table:string,user:string,ids:string[]){if(!supabase)return;let query=supabase.from(table).delete().eq('user_id',user);if(ids.length)query=query.not('id','in',`(${ids.join(',')})`);const {error}=await query;if(error)throw error}

export const supabaseDiaryRepository:DiaryRepository={
 async load(){
  if(!supabase)return cloneDefaults();const client=supabase;await userId();const [eventsRes,entriesRes,imagesRes,commentsRes,boardsRes,nodesRes,edgesRes,checklistRes,profileRes,connectionRes,preferencesRes,goalsRes,tasksRes]=await Promise.all([client.from('planner_events').select('*'),client.from('diary_entries').select('*'),client.from('diary_images').select('*').order('sort_order'),client.from('diary_comments').select('*'),client.from('brainstorm_boards').select('*'),client.from('brainstorm_nodes').select('*'),client.from('brainstorm_edges').select('*'),client.from('checklist_items').select('*'),client.from('profiles').select('*').maybeSingle(),client.from('calendar_connections').select('account_email,calendar_id,auto_sync,updated_at').eq('provider','google').maybeSingle(),client.from('user_preferences').select('*').maybeSingle(),client.from('study_goals').select('*'),client.from('study_tasks').select('*')]);
  for(const result of [eventsRes,entriesRes,imagesRes,commentsRes,boardsRes,nodesRes,edgesRes,goalsRes,tasksRes])if(result.error)throw result.error
  const imageRows=await Promise.all((imagesRes.data??[]).map(async row=>{const signed=await client.storage.from('diary-images').createSignedUrl(row.storage_path,3600);return{id:row.id,entryId:row.entry_id,fileName:row.file_name,dataUrl:signed.data?.signedUrl??'',storagePath:row.storage_path,sortOrder:row.sort_order,createdAt:row.created_at}}))
  const entries=(entriesRes.data??[]).map(row=>({id:row.id,eventId:row.event_id,title:row.title,body:row.body,mood:row.mood,tags:row.tags??[],images:imageRows.filter(img=>img.entryId===row.id),createdAt:row.created_at,updatedAt:row.updated_at}));
  const boards=(boardsRes.data??[]).map(row=>({id:row.id,name:row.name,nodes:(nodesRes.data??[]).filter(n=>n.board_id===row.id).map(n=>({id:n.id,boardId:n.board_id,title:n.title,body:n.body,color:n.color,x:n.x,y:n.y,width:n.width,height:n.height,createdAt:n.created_at,updatedAt:n.updated_at})),edges:(edgesRes.data??[]).filter(e=>e.board_id===row.id).map(e=>({id:e.id,boardId:e.board_id,sourceId:e.source_id,targetId:e.target_id,createdAt:e.created_at})),blocks:Array.isArray(row.blocks)?row.blocks:[],createdAt:row.created_at,updatedAt:row.updated_at}));
  const checklists=(checklistRes.data??[]).map((row:any)=>({id:row.id,date:row.date,text:row.text,done:row.done,sortOrder:row.sort_order,color:row.color??undefined,createdAt:row.created_at,updatedAt:row.updated_at,deletedAt:row.deleted_at??undefined}));
  const profile=profileRes.data?{displayName:profileRes.data.display_name,handle:profileRes.data.handle,avatar:'',timezone:profileRes.data.timezone,defaultEventDuration:profileRes.data.default_event_duration,defaultReminder:profileRes.data.default_reminder}:DEFAULT_DIARY_DATA.profile;
  const calendar={...DEFAULT_DIARY_DATA.calendar,...(preferencesRes.data?.calendar_options??{}),googleConnected:Boolean(connectionRes.data),googleEmail:connectionRes.data?.account_email??'',googleCalendarId:connectionRes.data?.calendar_id??'primary',autoSync:connectionRes.data?.auto_sync??false,lastSyncedAt:connectionRes.data?.updated_at};return{events:(eventsRes.data??[]).map(row=>camelEvent(row)),entries,comments:(commentsRes.data??[]).map(row=>({id:row.id,entryId:row.entry_id,body:row.body,createdAt:row.created_at,updatedAt:row.updated_at})),boards:boards.length?boards:[{...DEFAULT_DIARY_DATA.boards[0],id:crypto.randomUUID(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}],checklists,profile,calendar,preferences:preferencesRes.data?camelPreferences(preferencesRes.data):structuredClone(DEFAULT_DIARY_DATA.preferences),studyGoals:(goalsRes.data??[]).map(camelGoal),studyTasks:(tasksRes.data??[]).map(camelTask),dailyMemos:preferencesRes.data?.daily_memos??{},dateBrainstorms:preferencesRes.data?.date_brainstorms??{}}
 },
 async save(data){
  if(!supabase)return;const user=await userId();const errors:unknown[]=[];const run=async(promise:PromiseLike<{error:unknown}>)=>{const result=await promise;if(result.error)errors.push(result.error)};
  await run(supabase.from('profiles').upsert({user_id:user,display_name:data.profile.displayName,handle:data.profile.handle.replace(/^@/,'')||`diary_${user.slice(0,8)}`,timezone:data.profile.timezone,default_event_duration:data.profile.defaultEventDuration,default_reminder:data.profile.defaultReminder},{onConflict:'user_id'}));
  await run(supabase.from('user_preferences').upsert(snakePreferences(data.preferences,user,data.calendar,data.dailyMemos,data.dateBrainstorms),{onConflict:'user_id'}));
  if(data.events.length)await run(supabase.from('planner_events').upsert(data.events.map(event=>snakeEvent(event,user))));
  if(data.entries.length)await run(supabase.from('diary_entries').upsert(data.entries.map(entry=>({id:entry.id,user_id:user,event_id:entry.eventId,title:entry.title,body:entry.body,mood:entry.mood,tags:entry.tags,created_at:entry.createdAt,updated_at:entry.updatedAt}))));
  if(data.comments.length)await run(supabase.from('diary_comments').upsert(data.comments.map(comment=>({id:comment.id,user_id:user,entry_id:comment.entryId,body:comment.body,created_at:comment.createdAt,updated_at:comment.updatedAt}))));
  if(data.boards.length)await run(supabase.from('brainstorm_boards').upsert(data.boards.map(board=>({id:board.id,user_id:user,name:board.name,blocks:board.blocks??[],created_at:board.createdAt,updated_at:board.updatedAt}))));
  if(data.checklists.length)await run(supabase.from('checklist_items').upsert(data.checklists.map(item=>({id:item.id,user_id:user,date:item.date,text:item.text,done:item.done,sort_order:item.sortOrder,color:item.color,created_at:item.createdAt,updated_at:item.updatedAt,deleted_at:item.deletedAt}))));
  if(data.studyGoals.length)await run(supabase.from('study_goals').upsert(data.studyGoals.map(goal=>snakeGoal(goal,user))));if(data.studyTasks.length)await run(supabase.from('study_tasks').upsert(data.studyTasks.map(task=>snakeTask(task,user))));
  const nodes=data.boards.flatMap(board=>board.nodes),edges=data.boards.flatMap(board=>board.edges);if(nodes.length)await run(supabase.from('brainstorm_nodes').upsert(nodes.map(node=>({id:node.id,user_id:user,board_id:node.boardId,title:node.title,body:node.body,color:node.color,x:node.x,y:node.y,width:node.width,height:node.height,created_at:node.createdAt,updated_at:node.updatedAt}))));if(edges.length)await run(supabase.from('brainstorm_edges').upsert(edges.map(edge=>({id:edge.id,user_id:user,board_id:edge.boardId,source_id:edge.sourceId,target_id:edge.targetId,created_at:edge.createdAt}))));
  for(const entry of data.entries)for(const image of entry.images){let path=image.storagePath;if(!path&&image.dataUrl){path=`${user}/${entry.id}/${image.id}-${image.fileName.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const blob=await fetch(image.dataUrl).then(r=>r.blob());const uploaded=await supabase.storage.from('diary-images').upload(path,blob,{upsert:true,contentType:blob.type});if(uploaded.error)errors.push(uploaded.error)}if(path)await run(supabase.from('diary_images').upsert({id:image.id,user_id:user,entry_id:entry.id,storage_path:path,file_name:image.fileName,sort_order:image.sortOrder,created_at:image.createdAt}))}
  const images=data.entries.flatMap(entry=>entry.images);await removeMissing('checklist_items',user,data.checklists.map(v=>v.id));await removeMissing('diary_images',user,images.map(v=>v.id));await removeMissing('diary_comments',user,data.comments.map(v=>v.id));await removeMissing('diary_entries',user,data.entries.map(v=>v.id));await removeMissing('brainstorm_edges',user,edges.map(v=>v.id));await removeMissing('brainstorm_nodes',user,nodes.map(v=>v.id));await removeMissing('brainstorm_boards',user,data.boards.map(v=>v.id));await removeMissing('study_tasks',user,data.studyTasks.map(v=>v.id));await removeMissing('study_goals',user,data.studyGoals.map(v=>v.id));if(errors.length)throw errors[0]
 },
 async clear(){if(!supabase)return;const user=await userId();const stored=await supabase.storage.from('diary-images').list(user,{limit:1000});if(stored.data?.length)await supabase.storage.from('diary-images').remove(stored.data.map(item=>`${user}/${item.name}`));for(const table of ['checklist_items','diary_comments','diary_images','diary_entries','brainstorm_edges','brainstorm_nodes','brainstorm_boards','study_tasks','study_goals','calendar_sync_states','calendar_connections','calendar_feed_tokens','planner_events','user_preferences','profiles'])await removeMissing(table,user,[])}
}

export const diaryRepository:DiaryRepository=DEMO_MODE?localDiaryRepository:supabaseDiaryRepository

export function validateDiaryData(value: unknown): DiaryData {
  if(!value||typeof value!=='object')throw new Error('Invalid diary data')
  const data=value as Partial<DiaryData>
  if(!Array.isArray(data.events)||!Array.isArray(data.entries)||!Array.isArray(data.comments)||!Array.isArray(data.boards))throw new Error('Missing diary collections')
  const boards=(data.boards.length?data.boards:cloneDefaults().boards).map(board=>({...board,blocks:Array.isArray(board.blocks)?board.blocks:[]}))
  return { events:data.events,entries:data.entries,comments:data.comments,boards,checklists:Array.isArray(data.checklists)?data.checklists:[],profile:{...DEFAULT_DIARY_DATA.profile,...data.profile},calendar:{...DEFAULT_DIARY_DATA.calendar,...data.calendar},preferences:{...DEFAULT_DIARY_DATA.preferences,...data.preferences},studyGoals:Array.isArray(data.studyGoals)?data.studyGoals:[],studyTasks:Array.isArray(data.studyTasks)?data.studyTasks:[],dailyMemos:data.dailyMemos&&typeof data.dailyMemos==='object'?data.dailyMemos:{},dateBrainstorms:data.dateBrainstorms&&typeof data.dateBrainstorms==='object'?data.dateBrainstorms:{} }
}
