export type EventStatus = 'planned' | 'done' | 'cancelled'
export type SyncStatus = 'local' | 'synced' | 'pending' | 'conflict' | 'error'

export interface PlannerEvent {
  id: string; title: string; description: string; startAt: string; endAt: string; allDay: boolean
  color: string; location: string; status: EventStatus; recurrenceRule: string; reminderMinutes?: number
  source: 'local' | 'google'; googleSync: boolean; externalProvider?: string; externalCalendarId?: string
  externalEventId?: string; externalUpdatedAt?: string; lastSyncedAt?: string; syncStatus: SyncStatus
  syncError?: string; deletedAt?: string; createdAt: string; updatedAt: string
  textColor?: string; backgroundColor?: string; borderColor?: string
}
export interface DiaryImage { id: string; entryId: string; fileName: string; dataUrl: string; storagePath?: string; sortOrder: number; createdAt: string }
export interface DiaryEntry { id: string; eventId: string; title: string; body: string; mood: string; tags: string[]; images: DiaryImage[]; createdAt: string; updatedAt: string }
export interface DiaryComment { id: string; entryId: string; body: string; createdAt: string; updatedAt: string }
export interface BrainstormNode { id: string; boardId: string; title: string; body: string; color: string; x: number; y: number; width: number; height: number; createdAt: string; updatedAt: string }
export interface BrainstormEdge { id: string; boardId: string; sourceId: string; targetId: string; createdAt: string }
export type DocBlockType = 'title' | 'subtitle' | 'heading' | 'bullet' | 'body'
export interface DocBlock { id: string; type: DocBlockType; text: string }
export interface BrainstormBoard { id: string; name: string; nodes: BrainstormNode[]; edges: BrainstormEdge[]; blocks: DocBlock[]; createdAt: string; updatedAt: string }
export interface ChecklistItem { id: string; date: string; text: string; done: boolean; sortOrder: number; color?: string; createdAt: string; updatedAt: string; deletedAt?: string }
export interface DiaryProfile { displayName: string; handle: string; avatar: string; timezone: string; defaultEventDuration: number; defaultReminder: number }
export type PlannerDensity = 'relaxed' | 'default' | 'compact' | 'custom'
export type RolloverPolicy = 'none' | 'next-day' | 'reschedule' | 'ask'
export type StudyUnitType = 'page' | 'problem' | 'lecture' | 'chapter' | 'word' | 'minute' | 'hour' | 'custom'
export type StudyGoalStatus = 'active' | 'paused' | 'completed'
export type StudyTaskStatus = 'planned' | 'partial' | 'completed'

export interface UserPreferences {
  fontScale: number; plannerDensity: PlannerDensity; monthlyVisibleEventCount: number; monthlyVisibleTaskCount: number
  weeklyVisibleTaskCount: number; calendarCellHeight: number; eventCardGap: number; checklistRowHeight: number
  eventTitleMaxLines: number; memoSectionEnabled: boolean; memoSectionHeight: number; collapseCompletedTasks: boolean
  completedTaskLimit: number; defaultTextColor: string; defaultBackgroundColor: string; secondaryBackgroundColor: string
  accentColor: string; calendarLineColor: string; completedItemColor: string; selectedItemColor: string
  autoContrastEnabled: boolean; defaultBufferDays: number; defaultDailyStudyMinutes: number; defaultStudyWeekdays: number[]
  rolloverPolicy: RolloverPolicy; keepLockedTasksOnReschedule: boolean; recentColors: string[]
}

export interface StudyGoal {
  id: string; subject: string; title: string; unitType: StudyUnitType; customUnitLabel: string
  totalAmount: number; completedAmount: number; startDate: string; deadline: string; priority: number; difficulty: number
  minDailyAmount?: number; maxDailyAmount?: number; chunkSize: number; availableWeekdays: number[]; excludedDates: string[]
  restDates: string[]; dailyCapacity: Record<string, number>; estimatedMinutesPerUnit?: number; bufferDays: number
  dailyStartTime?: string; dailyEndTime?: string
  textColor: string; backgroundColor: string; borderColor: string; notes: string; autoScheduleEnabled: boolean
  googleSyncEnabled: boolean; appleFeedEnabled: boolean; status: StudyGoalStatus; createdAt: string; updatedAt: string; deletedAt?: string
}

export interface StudyTask {
  id: string; goalId: string; scheduledDate: string; title: string; startAmount: number; endAmount: number
  plannedAmount: number; completedAmount: number; estimatedMinutes: number; status: StudyTaskStatus; isLocked: boolean
  startTime?: string; sortOrder: number; textColor: string; backgroundColor: string; borderColor: string; notes: string; completedAt?: string
  externalProvider?: string; externalCalendarId?: string; externalEventId?: string; lastSyncedAt?: string
  createdAt: string; updatedAt: string; deletedAt?: string; isAutoGenerated: boolean
}

export interface CalendarPreferences {
  googleConnected: boolean; googleEmail: string; googleCalendarId: string; autoSync: boolean; lastSyncedAt?: string; appleToken: string
  googleContent: 'events' | 'study' | 'both'; googleIncludeCompleted: boolean; googleCompletedPrefix: boolean
  googleStudyTimeMode: 'all-day' | 'timed'; subjectCalendars: Record<string, string>; appleIncludeEvents: boolean
  appleIncludeStudy: boolean; appleIncludeCompleted: boolean; appleIncludeNotes: boolean; appleIncludeEstimatedTime: boolean
}
export interface DiaryData { events: PlannerEvent[]; entries: DiaryEntry[]; comments: DiaryComment[]; boards: BrainstormBoard[]; checklists: ChecklistItem[]; profile: DiaryProfile; calendar: CalendarPreferences; preferences: UserPreferences; studyGoals: StudyGoal[]; studyTasks: StudyTask[]; dailyMemos:Record<string,string>; dateBrainstorms:Record<string,DocBlock[]> }

export const DEFAULT_PREFERENCES: UserPreferences = {
  fontScale:100,plannerDensity:'default',monthlyVisibleEventCount:4,monthlyVisibleTaskCount:3,weeklyVisibleTaskCount:8,
  calendarCellHeight:138,eventCardGap:3,checklistRowHeight:36,eventTitleMaxLines:1,memoSectionEnabled:true,memoSectionHeight:58,
  collapseCompletedTasks:false,completedTaskLimit:5,defaultTextColor:'#252328',defaultBackgroundColor:'#fbfaf6',secondaryBackgroundColor:'#fffefa',
  accentColor:'#74539b',calendarLineColor:'#6f6b6f',completedItemColor:'#a54646',selectedItemColor:'#74539b',autoContrastEnabled:true,
  defaultBufferDays:0,defaultDailyStudyMinutes:180,defaultStudyWeekdays:[1,2,3,4,5,6,0],rolloverPolicy:'ask',keepLockedTasksOnReschedule:true,recentColors:[]
}

export const DEFAULT_DIARY_DATA: DiaryData = {
  events: [], entries: [], comments: [], checklists: [], boards: [{ id: 'default-board', name: 'My first board', nodes: [], edges: [], blocks: [], createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() }],
  profile: { displayName: 'Diary Keeper', handle: '@myday', avatar: '', timezone: 'Asia/Seoul', defaultEventDuration: 60, defaultReminder: 10 },
  calendar: { googleConnected: false, googleEmail: '', googleCalendarId: 'primary', autoSync: false, appleToken: '',googleContent:'both',googleIncludeCompleted:false,googleCompletedPrefix:true,googleStudyTimeMode:'all-day',subjectCalendars:{},appleIncludeEvents:true,appleIncludeStudy:true,appleIncludeCompleted:false,appleIncludeNotes:true,appleIncludeEstimatedTime:true },
  preferences: structuredClone(DEFAULT_PREFERENCES), studyGoals: [], studyTasks: [], dailyMemos:{}, dateBrainstorms:{}
}
