import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const esc=(value:string)=>(value??'').replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;')
const stamp=(value:string)=>value.replace(/[-:]/g,'').replace(/\.\d{3}/,'')
const hash=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))),byte=>byte.toString(16).padStart(2,'0')).join('')
const nextDay=(key:string)=>new Date(new Date(`${key}T00:00:00+09:00`).getTime()+86400000).toISOString().slice(0,10)

Deno.serve(async request=>{
 const token=new URL(request.url).pathname.split('/').at(-1)!;if(token.length<40)return new Response('Not found',{status:404})
 const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!),{data:feed}=await admin.from('calendar_feed_tokens').select('id,user_id').eq('token_hash',await hash(token)).is('revoked_at',null).single();if(!feed)return new Response('Not found',{status:404})
 const [{data:events},{data:preferences},{data:goals},{data:tasks}]=await Promise.all([admin.from('planner_events').select('*').eq('user_id',feed.user_id).is('deleted_at',null),admin.from('user_preferences').select('calendar_options').eq('user_id',feed.user_id).maybeSingle(),admin.from('study_goals').select('*').eq('user_id',feed.user_id).eq('apple_feed_enabled',true).is('deleted_at',null),admin.from('study_tasks').select('*').eq('user_id',feed.user_id).is('deleted_at',null)])
 const options=preferences?.calendar_options??{},lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//DEAR MY DIARY//Calendar//KO','CALSCALE:GREGORIAN','X-WR-CALNAME:DEAR MY DIARY','X-WR-TIMEZONE:Asia/Seoul']
 if(options.appleIncludeEvents!==false)for(const event of events??[]){lines.push('BEGIN:VEVENT',`UID:${event.id}@dear-my-diary`,`DTSTAMP:${stamp(event.updated_at)}`);if(event.all_day)lines.push(`DTSTART;VALUE=DATE:${event.start_at.slice(0,10).replaceAll('-','')}`,`DTEND;VALUE=DATE:${event.end_at.slice(0,10).replaceAll('-','')}`);else lines.push(`DTSTART:${stamp(event.start_at)}`,`DTEND:${stamp(event.end_at)}`);lines.push(`SUMMARY:${esc(event.title)}`,`DESCRIPTION:${esc(options.appleIncludeNotes===false?'':event.description)}`,`LOCATION:${esc(event.location)}`);if(event.recurrence_rule)lines.push(`RRULE:${event.recurrence_rule}`);lines.push('END:VEVENT')}
 if(options.appleIncludeStudy!==false){const goalIds=new Set((goals??[]).map(goal=>goal.id));for(const task of (tasks??[]).filter(task=>goalIds.has(task.goal_id)&&(options.appleIncludeCompleted||task.status!=='completed'))){const description=[options.appleIncludeNotes!==false&&task.notes,options.appleIncludeEstimatedTime!==false&&`예상 소요 시간: ${task.estimated_minutes}분`].filter(Boolean).join('\n');lines.push('BEGIN:VEVENT',`UID:study-${task.id}@dear-my-diary`,`DTSTAMP:${stamp(task.updated_at)}`,`DTSTART;VALUE=DATE:${task.scheduled_date.replaceAll('-','')}`,`DTEND;VALUE=DATE:${nextDay(task.scheduled_date).replaceAll('-','')}`,`SUMMARY:${esc(`${task.status==='completed'?'[완료] ':''}${task.title}`)}`,`DESCRIPTION:${esc(description)}`,'END:VEVENT')}}
 lines.push('END:VCALENDAR');await admin.from('calendar_feed_tokens').update({last_accessed_at:new Date().toISOString()}).eq('id',feed.id);return new Response(lines.join('\r\n')+'\r\n',{headers:{'content-type':'text/calendar; charset=utf-8','cache-control':'private, max-age=300'}})
})
