import type { PlannerEvent, StudyGoal, StudyTask } from '../types'

export interface DistributionDay { date:string; amount:number; startAmount:number; endAmount:number; estimatedMinutes:number; conflictCount:number; isLocked:boolean; taskId?:string }
export interface DistributionResult { ok:boolean; days:DistributionDay[]; tasks:StudyTask[]; warnings:string[]; errors:string[]; total:number }

const DAY_MS=86400000
export const parseDateKey=(key:string)=>{const [year,month,day]=key.split('-').map(Number);return new Date(year,month-1,day)}
export const dateKey=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`
const datesBetween=(start:string,end:string)=>{const dates:string[]=[];for(let value=parseDateKey(start);value<=parseDateKey(end);value=new Date(value.getTime()+DAY_MS))dates.push(dateKey(value));return dates}
export const unitLabel=(goal:Pick<StudyGoal,'unitType'|'customUnitLabel'>)=>({page:'쪽',problem:'문제',lecture:'강',chapter:'챕터',word:'단어',minute:'분',hour:'시간',custom:goal.customUnitLabel||'개'}[goal.unitType])
export const taskRangeLabel=(goal:Pick<StudyGoal,'unitType'|'customUnitLabel'>,start:number,end:number)=>{
 const unit=unitLabel(goal);if(goal.unitType==='problem')return `${start}~${end}번`;if(goal.unitType==='lecture')return `${start}~${end}강`;return `${start}~${end}${unit}`
}

function eventConflicts(events:PlannerEvent[],key:string){return events.filter(event=>!event.deletedAt&&dateKey(new Date(event.startAt))===key).length}
function busyMinutes(events:PlannerEvent[],tasks:StudyTask[],goalId:string,key:string){const eventMinutes=events.filter(event=>!event.deletedAt&&dateKey(new Date(event.startAt))===key).reduce((sum,event)=>sum+(event.allDay?60:Math.max(0,(new Date(event.endAt).getTime()-new Date(event.startAt).getTime())/60000)),0);return eventMinutes+tasks.filter(task=>task.goalId!==goalId&&!task.deletedAt&&task.scheduledDate===key&&task.status!=='completed').reduce((sum,task)=>sum+task.estimatedMinutes,0)}
function taskFromDay(goal:StudyGoal,day:DistributionDay,sortOrder:number):StudyTask{const now=new Date().toISOString();return{id:day.taskId??crypto.randomUUID(),goalId:goal.id,scheduledDate:day.date,title:`${goal.subject} ${taskRangeLabel(goal,day.startAmount,day.endAmount)}`,startAmount:day.startAmount,endAmount:day.endAmount,plannedAmount:day.amount,completedAmount:0,estimatedMinutes:day.estimatedMinutes,status:'planned',isLocked:day.isLocked,sortOrder,textColor:goal.textColor,backgroundColor:goal.backgroundColor,borderColor:goal.borderColor,notes:'',createdAt:now,updatedAt:now,isAutoGenerated:true}}

export function distributeStudyGoal(goal:StudyGoal,existingTasks:StudyTask[]=[],events:PlannerEvent[]=[]):DistributionResult{
 const errors:string[]=[],warnings:string[]=[]
 if(goal.totalAmount<=0)errors.push('전체 분량은 0보다 커야 합니다.')
 if(goal.completedAmount<0||goal.completedAmount>goal.totalAmount)errors.push('완료 분량은 0 이상, 전체 분량 이하여야 합니다.')
 if(parseDateKey(goal.deadline)<parseDateKey(goal.startDate))errors.push('마감일은 시작일보다 빠를 수 없습니다.')
 if(errors.length)return{ok:false,days:[],tasks:[],warnings,errors,total:0}
 const locked=existingTasks.filter(task=>task.goalId===goal.id&&task.isLocked&&!task.deletedAt&&task.status!=='completed')
 const lockedRemaining=locked.reduce((sum,task)=>sum+Math.max(0,task.plannedAmount-task.completedAmount),0)
 const remaining=Math.max(0,goal.totalAmount-goal.completedAmount-lockedRemaining)
 const allDates=datesBetween(goal.startDate,goal.deadline)
 const maxIndex=Math.max(0,allDates.length-goal.bufferDays)
 const excluded=new Set([...goal.excludedDates,...goal.restDates])
 const eligible=allDates.slice(0,maxIndex).filter(key=>goal.availableWeekdays.includes(parseDateKey(key).getDay())&&!excluded.has(key)&&!locked.some(task=>task.scheduledDate===key))
 if(remaining>0&&!eligible.length)errors.push('선택한 기간에 공부 가능한 날짜가 없습니다.')
 const capacity=eligible.map(key=>{const weekday=String(parseDateKey(key).getDay()),configured=goal.dailyCapacity[weekday];const timeLimit=goal.estimatedMinutesPerUnit&&configured!==undefined?Math.floor(Math.max(0,configured-busyMinutes(events,existingTasks,goal.id,key))/goal.estimatedMinutesPerUnit):Infinity;return Math.max(0,Math.min(goal.maxDailyAmount??Infinity,timeLimit))})
 const finiteCapacity=capacity.reduce((sum,value)=>sum+(Number.isFinite(value)?value:remaining),0)
 if(finiteCapacity<remaining){const days=eligible.length,needed=days?Math.ceil(remaining/days):remaining;errors.push(`남은 ${days}일 동안 현재 하루 최대 분량으로는 ${remaining}${unitLabel(goal)}을 완료할 수 없습니다. 하루 최소 ${needed}${unitLabel(goal)}이 필요합니다.`)}
 if(errors.length)return{ok:false,days:locked.map(task=>({date:task.scheduledDate,amount:task.plannedAmount-task.completedAmount,startAmount:task.startAmount,endAmount:task.endAmount,estimatedMinutes:task.estimatedMinutes,conflictCount:eventConflicts(events,task.scheduledDate),isLocked:true,taskId:task.id})),tasks:locked,warnings,errors,total:lockedRemaining}
 const weights=eligible.map((key,index)=>{const conflicts=eventConflicts(events,key)+existingTasks.filter(task=>task.goalId!==goal.id&&!task.deletedAt&&task.scheduledDate===key&&task.status!=='completed').length;const urgency=1+((goal.priority+goal.difficulty-2)/40)*(1-index/Math.max(1,eligible.length-1));return Math.max(.2,urgency*(1-Math.min(.65,conflicts*.15)))})
 const amounts=eligible.map(()=>0),chunk=Math.max(1,Math.floor(goal.chunkSize||1));let left=remaining
 while(left>=chunk&&eligible.length){const totalWeight=weights.reduce((sum,weight,index)=>sum+(amounts[index]+chunk<=capacity[index]?weight:0),0);if(!totalWeight)break;let best=-1,bestScore=-Infinity;for(let index=0;index<eligible.length;index++){if(amounts[index]+chunk>capacity[index])continue;const desired=remaining*weights[index]/totalWeight;const score=desired-amounts[index]+weights[index]*.001;if(score>bestScore){best=index;bestScore=score}}if(best<0)break;amounts[best]+=chunk;left-=chunk}
 while(left>0){let best=-1,bestScore=-Infinity;for(let index=0;index<eligible.length;index++){if(amounts[index]+1>capacity[index])continue;const score=weights[index]/(amounts[index]+1);if(score>bestScore){best=index;bestScore=score}}if(best<0)break;amounts[best]++;left--}
 if(left)errors.push(`${left}${unitLabel(goal)}을 배분하지 못했습니다. 최대 분량이나 공부 가능 시간을 늘려 주세요.`)
 const minimum=goal.minDailyAmount;if(minimum&&amounts.some(amount=>amount>0&&amount<minimum))warnings.push(`일부 날짜의 분량이 하루 최소 ${minimum}${unitLabel(goal)}보다 적습니다.`)
 let cursor=goal.completedAmount+1
 const occupied=locked.map(task=>[task.startAmount,task.endAmount] as const).sort((a,b)=>a[0]-b[0])
 const skipOccupied=()=>{let hit=occupied.find(([start,end])=>cursor>=start&&cursor<=end);while(hit){cursor=hit[1]+1;hit=occupied.find(([start,end])=>cursor>=start&&cursor<=end)}}
 const days:DistributionDay[]=[]
 eligible.forEach((key,index)=>{const amount=amounts[index];if(!amount)return;skipOccupied();const start=cursor,end=cursor+amount-1;cursor=end+1;days.push({date:key,amount,startAmount:start,endAmount:end,estimatedMinutes:Math.round(amount*(goal.estimatedMinutesPerUnit??0)),conflictCount:eventConflicts(events,key)+existingTasks.filter(task=>task.goalId!==goal.id&&!task.deletedAt&&task.scheduledDate===key&&task.status!=='completed').length,isLocked:false})})
 for(const task of locked)days.push({date:task.scheduledDate,amount:task.plannedAmount-task.completedAmount,startAmount:task.startAmount,endAmount:task.endAmount,estimatedMinutes:task.estimatedMinutes,conflictCount:eventConflicts(events,task.scheduledDate),isLocked:true,taskId:task.id})
 days.sort((a,b)=>a.date.localeCompare(b.date)||a.startAmount-b.startAmount)
 const tasks=days.map((day,index)=>day.isLocked?locked.find(task=>task.id===day.taskId)!:taskFromDay(goal,day,index))
 return{ok:errors.length===0,days,tasks,warnings,errors,total:days.reduce((sum,day)=>sum+day.amount,0)}
}

export function createStudyGoal(input:Partial<StudyGoal>={}):StudyGoal{const today=dateKey(new Date()),now=new Date().toISOString(),deadline=new Date(parseDateKey(today).getTime()+6*DAY_MS);return{id:crypto.randomUUID(),subject:'',title:'',unitType:'page',customUnitLabel:'',totalAmount:0,completedAmount:0,startDate:today,deadline:dateKey(deadline),priority:3,difficulty:3,chunkSize:1,availableWeekdays:[1,2,3,4,5,6,0],excludedDates:[],restDates:[],dailyCapacity:{},bufferDays:0,textColor:'#252328',backgroundColor:'#f1ebf7',borderColor:'#74539b',notes:'',autoScheduleEnabled:true,googleSyncEnabled:false,appleFeedEnabled:true,status:'active',createdAt:now,updatedAt:now,...input}}
